### ISSUE TITLE
Virtual paging no rows overlay

### ISSUE THREAD

**Issue by jkwiz** [ceolter/ag-grid#1038]
I may be missing something - however, it seems that the no rows overlay does not appear when using virtual paging. Changing **only** paging from virtual to pagination makes it appear as expected. It does work if I manually call this.gridOptions.api.showNoRowsOverlay(). This is in an angular 2 project.

Thanks!

**Comment by ceolter** [comment]
that is as expected. you don't want to use an overlay when loading. that's is because the grid eager fetches the rows - so if you are scrolling down one row at a time, the grid can be loading the next page in a buffer and you never see the blank rows. or you could scroll so that half the rows are missing and half are present, but you don't want to block viewing the present rows while loading the others.

if you don't like this, you can always use the api to show and hide the overlay.
