### ISSUE TITLE
onCtrlAndA should not always prevent default

### ISSUE THREAD

**Issue by maxired** [ceolter/ag-grid#1049]
Hi,

I am trying to implement a custom text edit render.

Since I am basically implement a text input, I would like the custom `Ctrl+A` shortcut to select the text.
Looks like the [onCtrlAndA](https://github.com/ceolter/ag-grid/blob/c8e046eaff0b1f7940587609165e5d5606f050a4/src/ts/gridPanel/gridPanel.ts#L339)  method stop the propagation before the event reach my component.
Not sure if this is linked, but I am using react to render the component.

**Comment by ceolter** [comment]
what happens if you listen for the ctrl+A on your text editor, and then 'event.stopPropogation()'?

in theory that will work, as the grid calls event.preventDefault() (which stops the webpage selecting everyone on the page) when the event hits the grid - but if you prevent it from hitting the grid, then you should get what you want.

**Comment by maxired** [comment]
I am not sure why, when I receive the event, the preventDefault has already been called.

Anyway, I found a workaround : calling select() on my input field
