### ISSUE TITLE
Tree Select

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1058]
I'm experiencing some weird behavior when using ```rowSelection: true```, ```groupSelectsChildren:true``` and tree data enabled.

1. Click a row without tree data. Row is selected as expected.
2. Click a row with tree data. Row and children are selected as expected. But the previously selected row is not unselected. I believe this behavior should only occur with CTRL + click.

**Comment by randdusing** [comment]
Additionally, I'm not able to select a parent node by clicking it. I've tried with groupSelectsChildren equal to true, false and 'group'

**Comment by ceolter** [comment]
```rowSelection: true``` should be ```rowSelection: 'multiple'```

from the docs: rowSelection: Type of row selection, set to either 'single' or 'multiple' to enable selection.

i'm wondering if fixing this will fix most of your problems.

one item that is not working as you describe is click selection - click selection doesn't work for group rows. this is because double clicking the row where the group is displayed (assuming you are using the provided group cell renderer) will expand / collapse the group.

what you should consider doing is using checkbox selecton. if using the provided group cellRenderer, then do as follows:
```
groupColumnDef: {headerName: "Athlete", field: "athlete", width: 200,
        cellRenderer: 'group',
        cellRendererParams: {
            checkbox: true
        }}
```

it makes sense to use checkbox when groupSelectsChildren, otherwise there is no visual way to know if the group is half selected.
