### ISSUE TITLE
onColumnValueChanged Not Accurate

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1062]
onColumnValueChanged doesn't seem to work properly. With the tool panel open, I performed the steps below:

1. Drag Column A to Values. I see a ColumnChangeEvent fired with the columns and column properties set. The column's aggFunc equals sum. This works well.
2. Change the aggFunc to avg via the UI. I see a ColumnChangeEvent fired, but it doesn't have columns or column properties.
3. Drag Column A in values back  to the column list. I see a ColumnChangeEvent fired with columns and column properties set, but the column's aggFunc still equals the last value. Shouldn't this be null now?

**Comment by ceolter** [comment]
```Shouldn't this be null now?```
no.

there are two things at play:
1 - is the column one of the columns currently used in an aggregation. to check this, you get the list of value columns from the columnApi.getValueColumns()
2 - what is the agg func - to check this, you call column.getAggFunc()

when you add a column to the valueColumns[], if there is no aggFunc, it sets one up by default.

when you remove a column from valueColumns, it doesn't touch the aggFunc, so that it will be there if you later add to the set of valueColumns again.

**Comment by randdusing** [comment]
Shouldn't the ColumnChangeEvent fired at least have the column and columns properties set in step 2?

**Comment by ceolter** [comment]
changed, column now included in event, will be in next release.

however i observe, the same event is used for both interactions i mention above. to be correct, there should be a separate event for actions 1 and 2. hindsight.
