### ISSUE TITLE
The Performance Problem when scroll grid.

### ISSUE THREAD

**Issue by shikelong** [ceolter/ag-grid#1066]
I use ag-grid in a react project with the component `ag-grid-react`. And I find the scroll is slow. 

env: 
 chrome  v52.
 windows 10.

![2016-08-08_120627](https://cloud.githubusercontent.com/assets/4499997/17469156/5d66a130-5d61-11e6-8564-5739482d6cdd.png)

**Comment by randdusing** [comment]
I'm experiencing similar problems. If I scroll with the mouse wheel, scroll is pretty smooth. If I scroll by clicking and dragging the scroll bar, it's very jumpy.

**Comment by ceolter** [comment]
do you have dev mode on in your application? if yes, turn it off. it's reported that dev mode slows down the grid when using react cell renderers.

otherwise, you haven't provided enough info for me to do anything.

is the problem react specific? can you test same grid outside of react component?

are you using react cell renderers? if yes, does the problem persist when you do not use them?

are the examples on the ag-Grid website running faster for you? if yes, then what is it in your grid that is making the difference?

**Comment by shikelong** [comment]
I use the demo in [best-react-data-gri](https://www.ag-grid.com/best-react-data-grid/index.php) to run the chrome dev timeline tools.  When scroll by dragging the scroll bar. It's slow.

**Comment by ceolter** [comment]
it's working fast for me. so not sure what i can do.

**Comment by tamer1an** [comment]
Mouse wheel scrolling works just fine.

It's little bit stack when scroll initiates by page-down key rapidly
