### ISSUE TITLE
allow editing of floating rows, ie colDef.floatingCellEditor

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#1078]

**Comment by ataft** [comment]
When I use floating rows with a group (groupHideGroupColumns: true), the floating row data for the grouped row does not appear because the group column is defined as hidden. Basically, I want to put the text "Summary" at the bottom left of the floating row, like the attached image, but it gets hidden.

Is this issue related to #1078?

![image](https://cloud.githubusercontent.com/assets/11670864/18371538/f6e5ef82-75e9-11e6-8cfd-b1a40d8c2f77.png)

**Comment by ceolter** [comment]
``` the floating row data for the grouped row does not appear```
i'm confused - what do you mean?

the floating rows display a cell for each visible column, what else would you expect? 

(i think i'm just not following your description)

**Comment by ataft** [comment]
Oops, I meant to say the floating footer cell for a grouped COLUMN does not appear. In the screenshot below, there is no way to set data for the first cell (highlighted in red) in the floating footer, correct?

![image](https://cloud.githubusercontent.com/assets/11670864/18558081/8b634178-7b26-11e6-987c-21458dd5abab.png)

**Comment by ceolter** [comment]
"Oops, I meant to say the floating footer cell for a grouped COLUMN does not appear. In the screenshot below, there is no way to set data for the first cell (highlighted in red) in the floating footer, correct?"
=> the group cell renderer takes the data from the node - what you need to do is override this by providing your own cellRenderer for the footer.

```
gridOptions = {
  groupColumnDef: {
    floatingCellRenderer: /* put your renderer in here */
  }
}
```

sorry for delay, busy times

**Comment by lambda2331** [comment]
I still have the same issue when I switch off pivot mode and have group by some column.
Use pinnedRow to display total row.
