### ISSUE TITLE
5.x breaks autoSizeColumns

### ISSUE THREAD

**Issue by connorblack** [ceolter/ag-grid#1109]
It seems like that ag-grid ignores auto sizing of columns until they are visible.

We have a very wide table, and when calling `api.autoSizeColumns` it ignores columns no in the viewport.

Chrome Version 52.0.2743.116 (64-bit)
Mac OSX 10.11.6 (15G31)

**Comment by ceolter** [comment]
autoSizeColumns looks at the columns on the screen, and works out the width based on what it sees. It cannot see the columns that are not rendered due to column virtualisation so these are left out. What you are left with is enough 'packed' columns to fit your current page.

Column Virtualisation is the technique the grid uses to render large amounts of columns with degrading performance by only rendering columns that are visible due to the horizontal scroll positions. Eg the grid can have 1000 columns with only 10 rendered if the horizontal scroll is only showing 10 columns.

To get around this, you can turn off column virtualisation by setting grid property suppressColumnVirtualisation=true. So choice is yours - what do you want - column virtualisation working OR sizeColumnsToFit working.

**Comment by santosh-k1** [comment]
I have faced the same issue and used below concept to fix it-
Call the function on .`ag-body-viewport scroll `where we have call `gridOptions.columnApi.autoSizeColumns(allColumnIds);` api

```
$(".ag-body-viewport").scroll(function(){
var allColumnIds = [];
    columnDefs.forEach( function(columnDef) {
        allColumnIds.push(columnDef.field);
    });
	  gridOptions.columnApi.autoSizeColumns(allColumnIds);
	  console.log('value');
	  return false;
   });
```
