### ISSUE TITLE
Grid doesn't render in ag-grid-enterprise 5.3.0

### ISSUE THREAD

**Issue by mraible** [ceolter/ag-grid#1111]
I created a prototype with ag-grid-enterprise using 5.2.0 and got everything to work. Today, I tried to upgrade to 5.3.0 and my grid doesn't render. Upon further investigation, it does render, but it doesn't show. If I add `style="height: 100%"`, it doesn't work. Adding `style="height: 100vh"`, it works, but looks funny because the header doesn't have a gray background and the zebra stripes are off. I'm using the `ag-bootstrap` theme.

**Comment by ceolter** [comment]
your grid div must have size. the grid then fills the size you give it. if you had no height (looks like your old version had no height) then i don't know why it was working in the first place.

with regards the difference, i did see one regression break with web components, where i had to adjust the height in the web components demo. however all the other examples online showed no problems with height and the latest version.

otherwise, not enough info above to know whats wrong. i advise looking at your CSS to try and figure it out.

**Comment by franktroia** [comment]
I have encountered the same issue. The grid rendered with the appropriate height in 5.0.7, but in 5.3.0 it no longer happens.

**Comment by ceolter** [comment]
@franktroia it's gotta be the size. make sure the div you are trying to render into has height. if unsure, set the height to a specific pixel value (eg 500px, do not use %) and see if it works then. it sounds like your hosting app is not giving the div the size you intend.

**Comment by jadhavajay** [comment]
@ceolter I was also facing this issue with the latest version, but got it working after setting the height in "px". Any specific reason why we should use 500px instead of %age? Also, I do not understand how it was working in older versions? It works properly until version 5.2.0, but after that.

**Comment by ceolter** [comment]
```500px instead of %age?```
=> i don't know why it's not working when it was previously - all my examples didn't have any issues - so must be something in your setups that i don't have that you all have in common.

in my experience, the % doesn't work when you don't have heights set for the parent containers (divs) in your app. if the parent doesnt' have height, then the % won't work.
