### ISSUE TITLE
checkboxSelection - Ability to pre-select a checkbox based on the data.

### ISSUE THREAD

**Issue by mpetkov** [ceolter/ag-grid#1128]
I tried searching the documentation but couldn't find what I was looking for.  Is there a way to preselect a row that is using checkboxSelection based on the input data?  For example if the data in a row has .selected = true, can it select the checkbox?

**Comment by mpetkov** [comment]
I did the following but am not sure if this is correct way of doing it:
```
onGridReady(event:any){
    this.grid.api.getRenderedNodes().forEach(function (node:any) {
        node.setSelected(node.data.selected);
    });
  }
```

**Comment by ceolter** [comment]
do what the example ```Deep Dive Example - Using forEachNode``` does:
https://www.ag-grid.com/javascript-grid-selection/index.php

just change this bit:
```
        if (node.data.country === 'United States') {
            node.setSelected(true);
        }
```
to check what you want to check on your data

**Comment by koshkarov** [comment]
You can do that with cellRenderer:
`
cellRenderer: (params) => {
    if (iShouldBeSelectedFunction()) {
        params.node.setSelected(true);
    }
}
`

**Comment by zekehernandez** [comment]
the thing about using forEachNode is that it re-draws for each row you have, which is slow, it would be nice to batch update.
@koshkarov, that's a good suggestion and works well, but it only selects visible rows.

**Comment by kmwarter** [comment]
I hope this helps someone else as I struggled for a couple of days trying to find workarounds to this before I found this in the docs. I feel like this is a common enough use case and there are enough people who seem to have struggled with this on Stack Overflow and here that it may be good for this to be highlighted in a more obvious place in the docs. I saw many people implement setSelected and never saw multiple arguments. 

If you find yourself in need of using AG-Grid and you need to preselect checkboxes on your table based on prior data you may run into this problem: 

You want to use onSelectionChanged method to update state when the user actually makes updates to the checkboxes so you can submit their preferences to your backend.

But, if you update state in onSelectionChanged and then you use forEachNode to programmatically call setSelected on all nodes to conditionally select it or not you can run into an "excessive updates" error in React and/or lots of unnecessary rerendering since you onSelectionChanged every time setSelected is called in this case.

The solution: setSelected actually accepts several other arguments. The third argument will suppress the onSelectionChanged calls.

`
const onFirstDataRendered = (event: any) => {
  if (data.favoriteBands.length) {
    const favoriteBandsDictionary = Object.fromEntries(
      data.favoriteBands.map((favoriteBandName) => [favoriteBandName, true]),
    );

    // For each node is band name is in favorite bands dictionary then setSelected to true
   // use third argument to suppress my onSelectionChanged events during this process
    event.api.forEachNode((node: any) =>
      node.setSelected(favoriteBandsDictionary[node.data.bandName], true, true),
    );
  }
};
`

Notice the two other arguments. The third one is called "suppressFinishActions" and will suppress the excessive rerenders.

<img width="770" alt="Screen Shot 2023-03-28 at 12 21 38 AM" src="https://user-images.githubusercontent.com/22015257/228167957-1dc101b9-fa11-4d83-bc5b-c62d19a8422c.png">
