### ISSUE TITLE
Group cells are uneditable

### ISSUE THREAD

**Issue by kishoreabhishek** [ceolter/ag-grid#1138]
I saw the code which restricts the group node from editing. Can you please explain the reason for this. Are there any side effects if enable editing for group node.

RenderedCell.prototype.isCellEditable = function () {
            if (this.editingCell) {
                return false;
            }
            **// never allow editing of groups
            if (this.node.group) {
                return false;
            }**
            return this.column.isCellEditable(this.node);
        }

**Comment by ceolter** [comment]
this is because historically the grid was designed as a reporting tool, where the groups are aggregations on the underlying data. so it doesn't make sense to edit the groups.

we know the grid is used for other purposes now, and the requirement exists for editing the groups. the reason we have not changed it is time - we need to spend the proper time on this a review the design, possibly refactor to accommodate editing of groups (rather than hack a 'true/false' in ), put into examples (our tests) and document.

so yea, only reason it's not done is time from us.

**Comment by ceolter** [comment]
last release introduced editable group rows.
