### ISSUE TITLE
Container height not set automatically after 5.3.0

### ISSUE THREAD

**Issue by ninety7** [ceolter/ag-grid#1154]
Hello,

I've upgraded from v5.2.0 to 6.0.1 and found out that the container's height is not set automatically anymore when height is not specified on the container's styles. I found out that the problem happens since v5.3.0. When looking at changes between these 2 (5.2.0->5.3.0), I found out that there is a new `eFullWidthContainer` and its height is correctly set, but the variable `heightOfContainer` in line 7822 (ag-grid.js) is always receiving `0` instead of the correct height to assign on line 7840.

I don't know the grid's design very well so this is as far as I could get, hope you can help fix this issue.

**Comment by ceolter** [comment]
can you reproduce in a plunker? none of my examples were impacted by any change - so it must be something in your setup that has a difference???

**Comment by joequant** [comment]
I suspect that this has something to do with #1173

**Comment by ceolter** [comment]
yes, they sound the same. as with the other issue i mentioned:

i'm 99% sure the problem is with the height that you are setting on the div that contains ag-Grid.

either you are not giving the div height, or you are using % height and not specifying height for the parent it is in (this is needed for % height to work).

the grid fills the width and height of the div you give it. so inspect your dom and work out why the div the grid is in isn't getting it's proper height.

**Comment by BesatZardosht** [comment]
I am setting the container div height to a fixed height but I still have the same issue..
Please fix this

**Comment by BesatZardosht** [comment]
I figured out what was the problem. I had updated the ag-grid but still was pointing to the old css.
Updated the css and everything works great again! 
Thanks

**Comment by ceolter** [comment]
no feedback so assuming fixed.
