### ISSUE TITLE
can we export the entire data not only the visible?

### ISSUE THREAD

**Issue by alex3stones** [ceolter/ag-grid#1158]
right now as I know, what we can export is only visible data, can we export the entire data since we have datasource? if possible, how do we do? 

Thanks

**Comment by eikishi01** [comment]
I just tested the example in https://www.ag-grid.com/javascript-grid-export/index.php and I got all the data exported not just the visible data.

**Comment by alex3stones** [comment]
but if I use pagination, then the export data set are only from current page...

**Comment by eikishi01** [comment]
The only way to do that I think is creating your own method to call the complete data set from the server and the using some lib to export it, I haven't seen anything in agGrid that can do that when using pagination.

**Comment by alex3stones** [comment]
hmm, Thanks so much.

**Comment by ceolter** [comment]
sorry for not responding, busy times.

you are right, the way to do it is to get your server to export it.

the grid uses pagination because there is to much data to transfer from the server to the client. if you could bring all the data across, then you wouldn't need to use pagination in the first place, and then the export would just work.
