### ISSUE TITLE
Is it possible to add submenu to customized main menu?  

### ISSUE THREAD

**Issue by bright-sea** [ceolter/ag-grid#1171]
We need customize main menu in order to add more actions to that column. Use getMainMenuItems we can add our customize menu items, that's great but not great enough. As we need more actions which would be better to be arranged as a tree menu structure (or at least one sub menu level more). In the documents : https://www.ag-grid.com/javascript-grid-column-menu/index.php we saw a note states:

**It is not possible to customise sub menus. This is a feature that is not intended.**

Do you have plans to add support of customized sub menus? Before this feature being added, are there any workarounds for this?

This feature is quite important for our use case. Really appreciate if this feature is on the schedule.

**Comment by bright-sea** [comment]
Really appreciate if you can give some comments about the status of this feature. @ceolter  

I can see that the standard menu has submenus, so it seems add customize submenus is just few steps away (of course, maybe there are some blocks there I don't know ). 

We need add lots of customize menuitems on each columns, if this feature will come soon, we can wait for it. Otherwise, we may need to create another menu components. Since we are using react, we raised another issue at ag-grid-react https://github.com/ceolter/ag-grid-react/issues/38 , that issue will block our development to add customize header cell react component. 

So , we are hold at these two issues. If any one fixed, we will be fine. Or do you have any suggestion of workaround?

Thanks

**Comment by ceolter** [comment]
hi - submenu's is on our plan, but out list is long and this isn't near the top right now.

putting react into the sub menus is not on our plan.

what you could do to get around it is:
a) when user clicks a menu, you present your own popup with the different things you want them to choose between.
b) turn off the context menu and create your own using the cellContextMenu event, the event will have the original mouse event (so you can get x,y coordinates) and also the cell's data (ie which row and column).

ps if you are an enterprise customer, you will get fast turnaround on the members forum. it has been weeks since i last went through the github issues.

**Comment by ceolter** [comment]
oh - i closed as questions answered. there is another issue open for sub menus (or at least, it is on my private list here)

**Comment by anil1712** [comment]
also, can we add HTML type support for MenuItemDef "name" property, right now it is supporting only string type I wanted to show some HTML styled component there. 

```
export interface MenuItemDef {
    name: string; // Can we enhance support here to support JSX or HTMLElement too
    disabled?: boolean;
    shortcut?: string;
    action?: ()=>void;
    checked?: boolean;
    icon?: HTMLElement|string;
    subMenu?: (MenuItemDef|string)[];
    cssClasses?: string[];
    tooltip?: string;
}
```
