### ISSUE TITLE
Select All with virtual paging/scrolling

### ISSUE THREAD

**Issue by don-bluelinegrid** [ceolter/ag-grid#1181]
@ceolter 

I've set up a rid with virtual paging/scrolling, and it is working well. 

One thing that I don't really see accounted for, is how to do a "Select All" checkbox that interacts with rows in a virtual paging/scrolling model.

Specifically, if I would like to add a "Select All" checkbox into the header of the checkboxSelection column, and have the effect be that all row checkboxes are shown as selected when visible - how could we do this?  Can you provide any guidance?

I did see the section about using node.forEach(), but am not sure that's relevant for virtual rows.
https://www.ag-grid.com/javascript-grid-selection/index.php

Don

**Comment by ceolter** [comment]
this is not possible. for the grid to be able to select, it needs to have the rows in memory.

under normal operation, virtual pagination loads the rows as they are needed. when you select a row, it's put into the grid's row selection. if you scroll down and the row is no longer needed by the grid, it keeps the rows that are selected, but disposes of everything else. this is so that the grid can give you the selected rows that you want. however if you try to select all, then it doens't have access to any of the rows except a) what is loaded for displaying on screen and b) what is already selected.

if you want to have the rows selected as they come back, well then you are doing server side selection, this the grid cannot help you with. if you really really need it (i'd suggest you tell your users it's not possible) then you should ignore the grid's selection, implement your own, and do your own selection on the server side. you would also have to implement your own cellRenderer with your own checkbox selection logic.
