### ISSUE TITLE
how to disable header clicks sort in ag-grid

### ISSUE THREAD

**Issue by DuanHejin** [ceolter/ag-grid#1185]
@ceolter 
Hi, I'm new here. I hava a problem with ag-Grid. Please help me. (Forgive my poor english. =.= )

As the ag-Grid sorting, setting the opt.enablesorting true, this will allow header clicks and show sort icons and sort within the grid.

However, I prefer to set api.setSortModel manually in a popup mdoel window rather than header clicks. So I want header clicks was disabled by some ways. I have tried some ways to fix it, but any of them worked.

e.g. I setted the opt.enablesorting false, header clicks sort was be disabled. But meantime, api.setSortModel didn't work as well.

e.g. I used headerCellRenderer to custom headerCellTemplate, but also failed. Because the up down arrow was shown up when I click the header.

Are there any ways to help me to fix it ?

**Comment by DuanHejin** [comment]
I saw the ag-grid.js source code, I found that in the  `RenderedHeaderCell.prototype.setupSort` function, when enableSorting is false, the ag-grid will remove all of the sort elements, including `agSortAsc` , `agSortDesc` ,`agNoSort` . At the same time , the header click listener will be not added.

Actually , I only want the click listener is off, rather than both of them. If we add a new property to control the click listener add or not, and using the `enablesorting ` to  control the sort elements and click listener add or not, I think this will be more better.

**Comment by ceolter** [comment]
your analysis is correct. the grid doesn't allow what you are trying, just not something we thought about.

however you can provide your own header template. return a div object rather than html, that way you can then add your own logic (ie add or remove sort icons). then on the column, you can do:

```
  column.addEventListener('sortChanged', mySortChangedFunc);
```

then in your listener, add or remove the icons in your header.

if you don't have agHeaderCellLabel in your header, then the grid will not add the click listener.
