### ISSUE TITLE
Performance of grid with Rows having dropdown templates

### ISSUE THREAD

**Issue by AbdulAleem107** [ceolter/ag-grid#1192]
Hi @ceolter ,
I have a grid which only have 1000 rows and and 5 coloums. In 4 of those 5 columns i have cell templates, 2 are dropdown ,one is checkbox and one is text box. I also am defining some events on the dropdowns and checkboxes. This is causing the scroll to be very laggy. So i have added the Scroll lag true in the options.it improved the scroll speed by 50%.But still have a bit of lag and the grid have white color flickering evrytime i scroll.Please help me on this.

**Comment by ceolter** [comment]
if your custom cells are causing it to be slow, then you need to figure out what it is that is causing the slowness. that isn't something which is wrong with ag-Grid!! i'd suggest taking them out one by one, seeing where the problem is. maybe you can consider not showing the dropdowns and instead use ag-Grid editing features (or provide your own cell editor) - either way it means the dropdownds only appear when needed.

**Comment by AbdulAleem107** [comment]
are there any minimum system requirements for Ag-grid? because i tried loading the grid without any cell template still the issue persists.I am testing on a windows server 2008 r2 , 8gb ram, AMD Opteron 4 cores.
even the demo on ag-grid website it is laging.

**Comment by ceolter** [comment]
we don't have minimum requirements, once the browser works then the grid will work. as to how fast it will work - well Chrome and Firefox are much faster than Safari and Internet Explorer. IE is the slowest. The best advice I can give is implement a demo of what you want to do, then decide for yourself on your target platform.
