### ISSUE TITLE
startEditingCell fails for rows past number of rendered rows

### ISSUE THREAD

**Issue by scott-census** [ceolter/ag-grid#1209]
See plunker: https://plnkr.co/edit/Yk3mbUCJBoqsK6LWAVfZ?p=info

I'm trying to use api.startEditingCell() to open the grid ready to add new rows, and it only works when there are a small number or rows (16 or less, in my case). Problem is in RowRenderer.startEditingCell when it calls getComponentForCell, which uses the cell row index to index into the renderedRows array.

Also, note that startEditingCell is not listed in the documentation under GridAPI, and where it is mentioned in Cell Editing, it says the routine is called api.startEditing.

You guys are going a great job of churning out new features and fixing everything pronto, so I give you slack on catching up with the documentation ;-)

**Comment by ceolter** [comment]
have just fixed this, will be in next release.

**Comment by ceolter** [comment]
i've also fixed the docs, again for the next release

**Comment by mcenkar** [comment]
@ceolter this still seems to be an issue, but now with horizontal scroll.

If I want to start editing cell that's not visible because it's column is not shown then startEditingCell doesn't work.

https://plnkr.co/edit/caMGpeTlUaVTZlyqrlK3?p=preview

It starts editing 'Inc Rate' column, but if you remove line 98 (ensureColumnVisible) from script.js then it doesn't work anymore.
