### ISSUE TITLE
processCellCallback

### ISSUE THREAD

**Issue by mrjumpy** [ceolter/ag-grid#1229]
I have a column and its format is phone number, like `09xxx`
as you can see, there's leading zero there.
I use lodash pad, to let phone number to be `09xxx`, not just `String(phone) => 9xxx`
and =>
```processCellCallback: (param)=>{

``````
    switch (param.column.colId) {
      case 'phone': {
        return  _pad(param.value) ;
      }
      default: {
        return param.value;
      }
    }
  }```
``````

but the format still number.. when i export.
is it a bug?

thanks

**Comment by alhweiti** [comment]
First, open the file in text editor, and see if it has zeros, because excel might be processing your data and changing it (by removing leading zeros)..
If in text editor, zeros are not there, then it's an export issue. I dealt with something similar, basically:
If you use valuegetter to format data, that will affect your exported data, so use that function.
For your information, in case you don't want the exported data to have certain stuff(like if you have a column with links and you want to only show the text not the whole href tag) then use cellRenderer, instead of valuegetter.

Hope it helps.

Ahlam

**Comment by mrjumpy** [comment]
thanks
I found that there's a leading zero in csv file.
So, is it a excel problem? not ag-grid

**Comment by alhweiti** [comment]
Yes. It's excel then..

**Comment by alhweiti** [comment]
Try wrapping it in double quotes , maybe that will make excel keep the leading zero..

**Comment by ceolter** [comment]
yes it's excel, so closing this issue. thanks @alhweiti
