### ISSUE TITLE
GridOptions getRowClass (function) doesn't run when row data changes

### ISSUE THREAD

**Issue by coderash01** [ceolter/ag-grid#1264]
getRowClass does not get called when the data is applied to the rowNode. This is especially apparent when using the viewport rowModel.

**Comment by ceolter** [comment]
what you say is true, however it's working as intended. the problem is that the css classes would be added and never removed. eg if you returned 'my-blue' as a class first time around, and then the second time around you returned 'my-green', then the row will end up with both 'my-blue' and 'my-green' instead of green replacing blue.

this is where cellClassRules come into play, as they add logic for each class. in time we could add similar to rows, but for now it doesn't exist.

suggestion - can you use cellClassRules to achieve what you want?
https://www.ag-grid.com/javascript-grid-cell-styling/

**Comment by coderash01** [comment]
So it was the intention for this functionality to not be used with viewport?

**Comment by ceolter** [comment]
@coderash01 that is true, it was implemented before viewport came on the scene.

you could use cellClassRules, they get called again when data changes.

**Comment by jintoppy** [comment]
@ceolter: cellClassRules will refresh the complete grid cells (with AggridReact + Redux ) where as getRowClass will not re-render the complete grid rows. So, there is a lot of performance difference. Is there any any way, we can make sure, getRowClass will not append to the existing class instead do the replace?

**Comment by dstj** [comment]
Old question, but just for completion's sake (because I thought it was a bug too). Here is the official doc link: https://www.ag-grid.com/javascript-data-grid/row-styles/#refresh-of-styles

> ### Refresh of Styles 
> If you refresh a row, or a cell is updated due to editing, the rowStyle, rowClass and rowClassRules are all applied again. This has the following effect:

> **rowStyle**: All new styles are applied. If a new style is the same as an old style, the new style overwrites the old style.
> **rowClass**: All new classes are applied. Old classes are not removed so be aware that classes will accumulate. If you want to remove old classes, then use rowClassRules.
> **rowClassRules**: Rules that return true will have the class applied the second time. Rules that return false will have the class removed second time.
