### ISSUE TITLE
Scroll location jumps to an old scroll location after setRowData is called

### ISSUE THREAD

**Issue by SoyYoRafa** [ceolter/ag-grid#1315]
Hi,

A common use case of my team for ag-grid conveys issuing an AJAX every second or so, and setting the grid data with setRowData with the response. Most of the time, it is very fluid for the user to scroll between events that call setRowData. The user can't visually tell that setRowData was called. However, sometimes, if the user scrolls, it will then jump back to a prior location even without any data changes. That location it jumps to seems to always be the same. Resizing the grid seems to set it back in a good state. A different project of mine that uses 4.2.9 enterprise doesn't seem to be affected. I have been able to reproduce this with 6.2.1, 6.4.2, 7.0.2. It is present in both enterprise and free. This is issue is preventing me from moving forward from 4.2.9.

**Reproducing**
1. Go to [https://jsfiddle.net/rfernand/nm8eozye/22/](url)
2. Wait around 20 seconds.
3. Try scrolling up and down, stop in different locations.

It doesn't take me more than two to four attempts to reproduce it using the instruction above. If you can't reproduce it, I can take a video of my screen as proof.

**Comment by SoyYoRafa** [comment]
I believe that the issue was introduced between 5.1.2 and 5.0.7. I can reproduce it in 5.1.2 but I can't in 5.0.7.

**Comment by ceolter** [comment]
the reason this is happening is:
a) grid isn't designed for you to be updating data like this. if you want to update the data (rather than replace with totally different data) then you should be using the ```rowNode.setData(newData)``` method. this means you would have to go through each row individually using the api.forEachNode() method or something similar.
b) if you do want to do it, well the problem is the focused cell is interfering with the scroll. if you clear these before setting the data, it will fix it. depending on you use case, this may or may not be an option. you could then set the focus again afterwards ONLY if the row was visible.

this will work in the next version:
```
            api.clearFocusedCell(); // will be in v7.1.x
```

so now you can do this hack while waiting for clearFocusedCell() to be exposed:
```
            api.focusedCellController.clearFocusedCell(); // hack that will work now
```

to find out what rows are rendered, you can use ```api.getFirstRenderedRow()``` and ```api.getLastRenderedRow()```, then see the api for setting focused cell.
