### ISSUE TITLE
Retrigger getRowClass on setSort/FilterModel

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid#1316]
I'm using ```getRowClass()``` to add the class ```ag-row-child-last``` to the last child of a group. Works fine as long as no calls to ```api.setSortModel()``` or ```api.setFilterModel()``` are called. But if I call either one of those and the last child position changes, ```getRowClass()``` is never called again. This means the wrong row has the ```ag-row-child-last``` class added. This is easy enough to fix with ```api.refreshView()```, but I was wondering if changing the sort or filter model should trigger ```getRowClass()```

Or perhaps I can just use cellClassRules as indicated in #1264

**Comment by ceolter** [comment]
it wouldn't work, as getRowClass adds classes only, it doesn't remove classes. so in your case, once the class is assigned, it is always assigned.

if you must do this, you could use processRowPostCreate and add the class yourself directly.

add a listener to the model (eg modelUpdated) and recheck things yourself. but if adding a listener for each row, you should remove the listeners as the rows are removed as follows:
```params.addRenderedRowListener('renderedRowRemoved', function() {........cleanup here.....} )```
so that you are not constantly adding listeners to rows
