### ISSUE TITLE
Allow setting initial row number for Virtual DataSource

### ISSUE THREAD

**Issue by nkoterba** [ceolter/ag-grid#1345]
Hello -

We have a use case for ag-grid, where we display the contents of a file as an ag-grid with each line in the file being a row in the grid.

We have a requirement for a user to be able to open the file and immediately scroll/view a particular line number (e.g. think search result that points to line 372).

Unfortunately, the current default behavior of `VirtualPageCache`, always loads the first page regardless of what page we eventually scroll into view.

I believe the culprit, is the default behavior of the `init` method in the `VirtualPageCache`.  See code reference here: https://github.com/ceolter/ag-grid/blob/028edc69f044084bc99efb0c1d0e3126ca0a2b6e/src/ts/rowControllers/virtualPagination/virtualPageCache.ts#L51-L56

By default, the `VirtualPageCache` always fetches row **0**.

Is it possible to include an ag-grid option to set the initial row to load, versus defaulting to 0?

It would be nice while defining gridOptions or even the grid's DataSource, to provide an initial row or page value that is then checked, and if present, used in the `init` method versus just using a hard-coded default.

Thoughts?

In the meantime, we're exploring how to achieve this functionality in our `getRows` callback thru various checks and hacks...

**Comment by ceolter** [comment]
to jump to row, first make sure the viewport has the right number of rows:
api.setVirtualRowCount(2000);

then scroll to that row:
api.ensureIndexVisible(2000);

then up to you to ignore the load of the first page (just return a bunch of blank rows, or i think calling params.failCallback() will also do it - but you MUST call at least one of them, otherwise the grid will think the call is outstanding and there is a limit to the number of concurrent calls.
