### ISSUE TITLE
FEATURE: CellRenderer params to include a rowState or Virtual Page State

### ISSUE THREAD

**Issue by nkoterba** [ceolter/ag-grid#1357]
In addition to displaying an error overlay on a grid, we'd like to custom render an error icon in cells that failed to load in our virtual-paged datasource.

Unfortunately, other than iterating through all the pages in the entire VirtualPageCache and comparing each page's start/end rows with the currently rendering cell's rowIndex and then checking that page's state, there's no way to know if we should render "loading", "failed", or the actual formatted data.

While on small grids and with small page cache sizes, this performance hit on **EACH** cell render probably wouldn't be too horrific, on a much larger grid with large page cache sizes, iterating through all the cache pages on each cell render just to determine if the cell or even row is in "failed to load data" states intuitively sounds like a bad idea performance wise.

Am I missing something obvious and this feature is already present?

**Comment by ceolter** [comment]
i don't want to include model specific items in the params, as then that opens the gate to including far more things in the params. could end up with everything in there, by which case then i'd wonder why not just use the gridApi?

what would be nice is an api to get a page in the cache. however am slow to do that also, because we have plans to refactor that further, and once we expose something in the api, we are making breaking changes.

what you can do is this hack: given the index, you can work out the page number (page size % row index), then you can access the page as follows:
```api.virtualPageRowModel.virtualPageCache.pages[x]```
where x is the page number you want
