### ISSUE TITLE
sizeColumnsToFit() bug with horizontal scrollbar

### ISSUE THREAD

**Issue by uvtzxpm** [ceolter/ag-grid#1386]
Reproduction:
1. Go to https://www.ag-grid.com/javascript-grid-resizing/
2. In the example at the bottom, keep clicking the "Size to Fit" button.
3. The grid cannot decide on a constant size for the columns between calls to `sizeColumnsToFit()`. The problem might be related to the width of the vertical scrollbar.

GIF showing problem: http://i.imgur.com/Z8CajVQ.gif

I'm using the most recent Chrome (55.0.2883.87 m).

Probably related to: https://github.com/ceolter/ag-grid/issues/1333

I came across this problem because I'm trying to implement something like: https://github.com/ceolter/ag-grid/issues/627

**Comment by Ruud-cb** [comment]
+1 of course, indeed the same issue as #1333 , but then I try to do it automatically.

**Comment by Ruud-cb** [comment]
Found the issue, see PR

**Comment by uvtzxpm** [comment]
@Ruud-cb I can confirm that your PR seems to fix the problem for me. Thanks!

**Comment by nischi** [comment]
@Ruud-cb I found out that the issue only happens if you have a display with high dpi and the width is a floating value and not an integer. can you confirm that?

**Comment by Ruud-cb** [comment]
@nischi I have one iiyama proLite E2208HDD with a dpi of 100 and resolution of 1980x1080, and one old samsung syncMaster 940bw with a dpi of 96 and resolution of 1440x900. So if you have a screen with a lower dpi or face issues, please provide some more info on what is happening at yours.
Also, please check for yourself if it makes a difference for a floating value or integer. As far as I've seen, it was always an integer during debugging.
Perhaps take on this discussion in the PR itself.

**Comment by nischi** [comment]
@Ruud-cb I have a ASUS PB287Q with 3840x2160 and 157dpi. I have only the problem if the div in which the grid is has a float number like 2507.2. If i change that to 2507 or 2508 it works without blinking. So i think something with calculate the width is wrong if you have a width with a float-number.

**Comment by Ruud-cb** [comment]
@nischi Hmm.. well I've tried to change the container div of the grid with floating values, but this seems to have no real effect on the calculation, because it uses integer values. It eventually uses `clientWidth` which returns an int.
About the dpi, hmm maybe, but a phone has a dpi of somewhat 300, where I don't have the issue now.
Don't get me wrong though: It does sometimes have to recalculate the widths so that the scroll balks go away, but it eventually can make a decision and stick to one width, so that it is not flipping constantly. Please read #1333 , which was my issue, what got fixed.
Else I would kindly advise you to debug it a bit more, look at the same lines of code where I made changes and see the outcome.

**Comment by uvtzxpm** [comment]
@Ruud-cb This has been fixed for me in v7.2.2, does it fix your problem too?

https://www.ag-grid.com/change-log/changeLogIndex.php

- Bugfix: api.sizeColumnsToFit() was incorrectly working out the vertical scroll value - meant it was out by the scroll width sometimes in it's calculations.

@nischi I think you should open a new issue if your problem has not been solved in the new version.

**Comment by ceolter** [comment]
yes it's fixed in latest. i messed up some refactoring, the grid was checking if horizontal scroll was present when working out available width - it should use vertical scroll.
