### ISSUE TITLE
Set groupRemoveSingleChildren on column level

### ISSUE THREAD

**Issue by ha-decodeit** [ceolter/ag-grid#1565]
**I'm submitting a ...** 
```
[ ] bug report
[x] feature request
[ ] support request 
```

**Current behavior**
Currently the _groupRemoveSingleChildren_ property can only be set globally.

**Expected behavior**
The column definition should have a _groupRemoveSingleChildren_ property.

**What is the motivation / use case for changing the behavior?**
Depending on the grouped column the _groupRemoveSingleChildren_ behavior can be either true or false.

* **ag-Grid version:** X.X.X
Ag Grid Enterprise 8.2.0

**Comment by ceolter** [comment]
you can turn this property on / off yourself, so easy to add something to the grid that listens for changes in group columns and then sets this property, it's not needed to be in the grid on the column level.

**Comment by aparolini** [comment]
> you can turn this property on / off yourself, so easy to add something to the grid that listens for changes in group columns and then sets this property, it's not needed to be in the grid on the column level.

Can you explain precisly how to do this ? I want to set groupRemoveSingleChildren only for a column. Thanks in advance

**Comment by kiril-matev** [comment]
Hi @aparolini,

Here's how to set this mode conditionally depending on the column you're grouping by.

In this example, groupRemoveSingleChildren is set only if the only or the last column you're grouping by is COUNTRY. 

https://plnkr.co/edit/TY61ZHuJUYTuYTHv

1. Drag the COUNTRY column to the row group panel
**Actual & Expected**: Rows are grouped by country, and the group node for Russia is removed as it only has one child

2. Click the X button inside the COUNTRY item in the row group panel to remove grouping
3. Drag the AGE column to the row group panel

**Actual & Expected**: Rows are grouped by AGE values, and all groups have a single child but are not removed

In this example, groupRemoveSingleChildren is set based on the last column in the group by. However, you can modify this example to set the groupRemoveSingleChildren based on whether a specific column is grouped by even if it's not the last in the group column list.

I hope this helps.

**Comment by aparolini** [comment]
Thanks a lot, but this dosen't work along with  `groupDefaultExpanded: 1,`, as I nee to have the group expended by default.
Any idea ?

**Comment by aparolini** [comment]
Hello,
Tx for your answer. I will try to make a fork, but in the minetime here is what we need (As this is becoming as urgent matter for us). It's very simple:
* We have a grid with two columns A and B, that have "rowGroup = true", and all the other cols have "rowGroup= false"
* Column A need to have always gridOptions.groupRemoveSingleChildren = false ( never hide group)
* Column B need to have always gridOptions.groupRemoveSingleChildren = true ( hide if it has a single child)
* The grid must have all default groups expended
* We may choose to show column A, or B, or both  according user preferences.

**Comment by kiril-matev** [comment]
Hello @aparolini,

We use github to receive bug reports from the AG Grid community. We don't provide support via github and we cannot guarantee the response time here will allow you to resolve urgent matters.

As you're using AG Grid Enterprise functionality such as row grouping you already have an AG Grid Enterprise license, which gives you access to our support portal. In the future please submit a support case in our support system for this.

The **onColumnRowGroupChanged** event is fired when there's a change in a column definition from one **rowGroup** value to another. When you set the rowGroup=true as an initial value in the column definition, there's no actual change and the event doesn't get fired. This is expected behavior.

In order to get the **onColumnRowGroupChanged** event to fire, provide the column definitions ungrouped (not setting rowGroup=true), and in onGridReady group the grid by this column. This way there's a change in the column definition rowGroup property value and as a consequence the event is fired:
https://plnkr.co/edit/77tGlx8rajOisNK2

I hope this helps. This response is just to help you fire this event. If you need further help with implementing your larger scenario please submit a support case.

Thanks for reaching out!

**Comment by aparolini** [comment]
Hello @kiril-matev ,
It's now working correctly for me! Thanks a lot for your great feedback.
I didnt know this `addRowGroupColumn `API method.

The only small visual glitch I've seen, is that the grid is displayed in two steps: first without any group, then the groups appears, making the row to jump a bit. 

NOTE: I posted this issue to AG Grid Enterprise support site, but the answer was.: "there is no workaround we can think of".
https://ag-grid.zendesk.com/hc/en-us/requests/22010

So thanks a lot for this!

Cheers,
Antonio
