### ISSUE TITLE
Default filter on text fields now equals

### ISSUE THREAD

**Issue by jenb34** [ceolter/ag-grid#1643]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the latest version 9.1.0 the default filter type on text is "equals"

**Expected behavior**
In previous versions this has been "contains"

**Minimal reproduction of the problem with instructions**

Create a grid with a text column and add a filter/floating filter - the default selection is "equals"

**What is the motivation / use case for changing the behavior?**

Behaviour was different in previous versions so is confusing to users

**Please tell us about your environment:**

Windows, IntelliJ Ultimate

* **ag-Grid version:** X.X.X

Issue in 9.1.0 (not in 9.0.2)

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular2/Typescript

**Comment by R4DIC4L** [comment]
Experiencing the same issue with the new version (9.1.0) when using ag-grid in React. I believe most users would expect the default filtering using contains (as it was in older versions).

Maybe the grid could provide a way of setting the default filter/floating filter type on a column to the preferred type: equals, contains etc (didn't see a way to change that and changing the filter type order doesn't seem to affect the default). This is especially useful on floating filters where the user is less likely to go and change the filter type.

**Comment by makinggoodsoftware** [comment]
Hi!

Thanks for raising this, this is tracked by AG-486, it will be available in the next release.

Thanks

**Comment by henjovr** [comment]
AG Grid 11.0.0 has been released, but I see no mention of AG-486.
In which release will this be fixed?

**Comment by makinggoodsoftware** [comment]
Hi,

It seems like we missed this in the release notes.

In case you haven't noticed this is available now in ag-grid

Text
filterOptions: If specified, limits the amount of options presented in the filter UI, it must be a string array containing some of the following values {equals, notEqual, contains, notContains, startsWith, endsWith}
defaultOption: If specified, changes the default filter option to one of {equals, notEqual, contains, notContains, startsWith, endsWith}. If not specified the default type is {contains}, if {contains} is not available because is removed using filterOptions, then the default is the first item in the filterOptions

Number
filterOptions: If specified, limits the amount of options presented in the filter UI, it must be a string array containing some of the following values {equals, notEquals, lessThanOrEqual, greaterThan, greaterThanOrEqual, inRange}
defaultOption: If specified, changes the default filter option to one of {equals, notEquals, lessThanOrEqual, greaterThan, greaterThanOrEqual, inRange}. If not specified the default type is {equals}, if {equals} is not available because is removed using filterOptions, then the default is the first item in the filterOptions

https://www.ag-grid.com/javascript-grid-filter-text
https://www.ag-grid.com/javascript-grid-filter-number
