### ISSUE TITLE
autoSizeColumns api not worked for all columns in the grid

### ISSUE THREAD

**Issue by santosh-k1** [ceolter/ag-grid#1692]
i have try `autoSizeColumns` api  which is not working properly. issue is if i have 100 column in the  grid and autoSizeColumns api will auto resize only visual column and rest of scroll hidden columns is not resize..
![image](https://cloud.githubusercontent.com/assets/4470369/26817794/9fc26b44-4ab5-11e7-9355-1767aebaf483.png)

**Comment by uvtzxpm** [comment]
The answer is in the documentation: https://www.ag-grid.com/javascript-grid-resizing/#gsc.tab=0

> autoSizeColumns() looks at the rendered cells on the screen, and works out the width based on what it sees. It cannot see the columns that are not rendered due to column virtualisation. Thus it is not possible to autosize a column that is not visible on the screen.
> 
> Column Virtualisation is the technique the grid uses to render large amounts of columns with degrading performance by only rendering columns that are visible due to the horizontal scroll positions. Eg the grid can have 1000 columns with only 10 rendered if the horizontal scroll is only showing 10 columns.
> 
> To get around this, you can turn off column virtualisation by setting grid property suppressColumnVirtualisation=true. So choice is yours - what do you want - column virtualisation working OR auto-size working on off screen columns.

Turning off column virtualisation may negatively affect the performance of the grid if you have a lot of rows/columns.

**Comment by seanlandsman** [comment]
@uvtzxpm thanks

Closing as answered

**Comment by santosh-k1** [comment]
I have fixed the issue by using below code- 
Call the function on .`ag-body-viewport scroll` where we have call  `gridOptions.columnApi.autoSizeColumns(allColumnIds);` api
```
$(".ag-body-viewport").scroll(function(){
var allColumnIds = [];
    columnDefs.forEach( function(columnDef) {
        allColumnIds.push(columnDef.field);
    });
	  gridOptions.columnApi.autoSizeColumns(allColumnIds);
	  console.log('value');
	  return false;
   });
```

**Comment by pscanlon1** [comment]
suppressColumnVirtualisation should be the default! I just found this and my life is now saved.

**Comment by jjloneman** [comment]
I've struggled with a solution for a while now, since I want the benefits of column virtualization and auto-sized columns only on the initial render, but finally figured out a workaround where you can still achieve both.

**Generic solution**

1. Whenever the grid is ready ([`gridReady`](https://www.ag-grid.com/javascript-grid-events/#miscellaneous) callback, for instance) call [`api.sizeColumnsToFit()`](https://www.ag-grid.com/javascript-grid-api/#columns) to cram all the columns to fit into the initial width of the grid.
2. Then, for the [`firstDataRendered`](https://www.ag-grid.com/javascript-grid-events/#miscellaneous) callback, call [`columnApi.autoSizeColumns(colIds)`](https://www.ag-grid.com/javascript-grid-column-api/#column-keys).

**React solution**

[My working Plunkr example](https://next.plnkr.co/edit/lJeRgiNC1siGl0zA) that I forked from [ag-grid's docs example](https://www.ag-grid.com/javascript-grid-resizing/#sizing-columns-by-default).

Here is a generic snippet for a React solution:

```javascript
import React from "react";
import { AgGridReact } from "ag-grid-react";

export default Grid = () => {
  /**
   * Auto-size all columns once the initial data is rendered.
   */
  const autoSizeColumns = params => {
    const colIds = params.columnApi
      .getAllDisplayedColumns()
      .map(col => col.getColId());

    params.columnApi.autoSizeColumns(colIds);
  };

  /**
   * Cram all columns to fit into the grid initially.
   */
  const onGridReady = params => {
    params.api.sizeColumnsToFit();
  };

  return (
    <AgGridReact
      onGridReady={onGridReady}
      onFirstDataRendered={autoSizeColumns}
      //...
    />
  );
};
```

**Note for Angular**

Instead of using `gridReady`, use `AfterViewInit` as stated in the [docs](https://www.ag-grid.com/angular-more-details/):

> Sometimes the `gridReady` grid event can fire before the Angular component is ready to receive it, so in an Angular environment its safer to rely on `AfterViewInit` instead before using the API.

**Comment by nikhilknoldus** [comment]
@jjloneman the above solution is not working for tree view columns (drill downs). Any suggestion for that ?

**Comment by ClayShentrup** [comment]
> suppressColumnVirtualisation should be the default!

_Certainly_ not.

**Comment by hoangdinhcong** [comment]
> @jjloneman the above solution is not working for tree view columns (drill downs). Any suggestion for that ?

hi @nikhilknoldus , did you find solution for this 🥲
