### ISSUE TITLE
Grid state when changing data

### ISSUE THREAD

**Issue by dejanberic** [ceolter/ag-grid#17]
Currently if I filter the grid on one column and after that I change rowData and refresh the grid, the filtering is still there which is good, but if I sort the collumn, change rowData and refresh the grid, the columns will not have sorting enabled the way I sorted them in the first place.

So, in short, state of grid is saved for filtering but not for sorting.

I think it should also save the state for sorting but for those users of angular grid  that want to reset state for these maybe the api could have methods like: resetFiltering, resetSort on angular grid.

**Comment by ceolter** [comment]
makes sense, sorting order should stay between row loads. the current behavious wasn't by design, just came together that way. btw - i'm at a loss what to do with 'set filter' between row loads, as loading new rows changes the filter (ie the list of items to select from changes), so not sure how best to manage this, it probably should be managed differently based on the domain (eg someone might filter on 'country' which will stay the same between row sets, however 'person name' would be different set between row sets).

**Comment by dejanberic** [comment]
Maybe you can decide on one logic for managing set filter but give the opportunity to override that behavior if desired by a user of angular grid.One way of managing them is to add those to the set that were not shown previously i.e. not filtered out previously.

**Comment by ceolter** [comment]
this was done months back. filters now have parameter newRowsAction to keep state between grid loads.
