### ISSUE TITLE
error TS2559: Type 'GroupCellRenderer' has no properties in common with type 'ICellRenderer'.

### ISSUE THREAD

**Issue by timfogarty-deluxe** [ceolter/ag-grid#1708]
ag-grid and ag-grid-angular at 10.1.0, upgraded Angular to 4.2.2, recompiled.  Got following error

node_modules/ag-grid/dist/lib/rendering/cellRenderers/groupCellRenderer.d.ts(6,22): error TS2559: Type 'GroupCellRenderer' has no properties in common with type 'ICellRenderer'.

**Comment by matthewmeyer** [comment]
I just started getting this too. Typescript just updated to 2.4.0 I reverted Typescript to 2.3.4 and the error is gone. Each version of Typescript seems to get better and better at flagging errors, it is probably a valid issue but you can workaround with a more lenient Typescript.

**Comment by makinggoodsoftware** [comment]
It seems 2.4 is a RC?

https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/

I can not understand what this error is trying to address, iCellRenderer has only an optional method, not sure how anyone implementing it can break the interface.

In my opinion this is a bug on their end, we are going to close this until 2.4 is not RC and then we will check again

**Comment by makinggoodsoftware** [comment]
Upon further reading of the release notes of 2.4 I can see this is intentional..

Weak types:

Back in TypeScript 1.6, we added a check for excess properties in object literals. This check looked for unexpected properties in object literals, and it happened to catch a large class of bugs. The only shortcoming of the check was that if you didn’t immediately pass your object literal to something of the appropriate type, the check wouldn’t be triggered.

In TypeScript 2.4, we’re adding a similar check for what we call weak types. Any type that contains only optional properties is considered a weak type since it provides few restrictions on what can be assigned to it. For example, this Options type is a weak type:

https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/

They include a workaround...

Since this is a breaking change, you may need to know about the workarounds which are the same as those for strict object literal checks:

Declare the properties if they really do exist.
Add an index signature to the weak type (i.e. [propName: string]: {}).
Use a type assertion (i.e. opts as Options).

So your implementation since 2.4 is going to have to include the method that is optional (refresh) even if you are going to leave it empty (same as not implementing it pre 2.4)


For the record... I think this is crazy... 😞

**Comment by jamesBennett** [comment]
I'm getting a similar error with 2.4
TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.

**Comment by RyanCavanaugh** [comment]
@makinggoodsoftware I think you've misapprehended the problem here. Your .d.ts file has a bug in it.

If you write
```ts
interface Foo {
  blah()?: void;
}
class Bar implements Foo {
}
```
The `implements` clause` **does nothing**. It does not cause a `blah?(): void` property to appear in `Bar`. There's no way this is what you intended to mean.

You should write this instead if you want to "copy down" optional properties into the class:
```ts
interface Foo {
  blah()?: void;
}
class Bar {
}
interface Bar extends Foo { }
```

**Comment by talynone** [comment]
Since TypeScript 2.4.1 is now out this issue should be revisited.

**Comment by jonfasking** [comment]
I for one appreciate this enhancement because it immediately exposed some questionable ways I was using generics. In addition it brought to light some redundant implementations that had previously been overlooked, there was nothing technically wrong but it didn't make any sense.

@RyanCavanaugh I understand your first point about the implementation declaration being redundant. However, your proposed solution, even if that technically works and is valid, it probably shouldn't be used. It's literally showing someone how to reverse abstractions and implement a solution that goes against everything an interface is designed to do.

**Comment by guryanovev** [comment]
> @Mani2693 why would you downvote @RyanCavanaugh suggestion? That is an ideal to solution.

Actually it is not, for example consider the case with interface like this:

    interface IDisposable {
        dispose?: () => void;
    }

And consider there are a lot of classes that *could* have (optional) `dispose` method. I do not want to go over ALL the classes and explicitly make them implement IDisposable or create an interface for every class as only few of them actually need to have `dispose` implementation. That just kills the pretty of duck-typing we had it before.

**Comment by RyanCavanaugh** [comment]
@guryanovev can you clarify with a longer example?

**Comment by splintor** [comment]
@guryanovev Stating that a class implements your `IDisposable` interface tells nothing to the compiler.
Instead, you should make the `dispose` method non-optional, and then make only classes that need to have dispose implementation implement `IDisposable` - and then, if they fail to implement it (e.g mistype `dispose`, the compiler will warn you.
 
If needed, you can have an `ICanBeDisposable` interface that has an optional `dispose` method:
```
interface ICanBeDisposable {
    dispose?(): void;
}
```
Which you would pass to a method that will call `dispose()` if it exists on the object, but because of duck-typing, you don't actually need to specify that your objects implements `ICanBeDisposable` - because it is a Weak Type, *all objects* implement it.

**Comment by guryanovev** [comment]
> Stating that a class implements your IDisposable interface tells nothing to the compiler.

100% agree

> you don't actually need to specify that your objects implements ICanBeDisposable - because it is a Weak Type, all objects implement it.

This is the point, since v2.4 of Typescript I must make my class implement ICanBeDisposable otherwise I get compiler errors at some cases.

**Comment by RyanCavanaugh** [comment]
```ts
interface IDisposable {
  dispose(): void;
}

function fn(x: IDisposable | { dispose?: never; }) {
  if ((x as IDisposable).dispose) {
    x.dispose();
  }
}

class Foo implements IDisposable {
  dispose(): void { }
}

class Bar  { // Bad IDisposable impl
  dispose(count: number): void { }
}

class Baz  {
}

fn(new Foo()); // OK
fn(new Bar()); // Error
fn(new Baz()); // OK
```

**Comment by MrKou47** [comment]
@jamesBennett i have the same problem! how to solve it?

**Comment by splintor** [comment]
@RyanCavanaugh - I didn't understand what your code is demonstrating.

@guryanovev Can you give an example? Because I don't see what compiler errors you get.

Here is the code as I see it
```
interface IDisposable {
  dispose(): void;
}

interface ICanBeDisposable {
  dispose?(): void;
}

function fn(x: ICanBeDisposable) {
  if (x.dispose) {
    x.dispose();
  }
}

class Foo implements IDisposable {
  dispose(): void { }
}

class Bar  {
  doSomething(): void { }
}

fn(new Foo()); // OK
fn(new Bar()); // OK
```

**Comment by guryanovev** [comment]
@splintor 

Just tried your code with tsc v2.4 and got this:

    index.ts(24,4): error TS2559: Type 'Bar' has no properties in common with type 'ICanBeDisposable'.

With v2.3 it would work

**Comment by splintor** [comment]
Are you sure? That's strange, as in my code, I didn't wrote that `Bar` implements `ICanBeDisposable`. What's line 24?

**Comment by guryanovev** [comment]
@splintor 

Line 24 is

    fn(new Bar()); // Error

That is the breaking change with weak types typescript introduced in v2.4

> I didn't wrote that Bar implements ICanBeDisposable.

and that caused the problem, you must explicitly implement `ICanBeDisposable` interface to avoid compiler errors since v2.4 of tsc.

**Comment by splintor** [comment]
@guryanovev 
Oh yes, I somehow missed that. Sorry.

I now realize that the compiler has nothing to check when the parameter of a function is of weak type, so `function fn(x: ICanBeDisposable) {...}` is equivalent to `function fn(x: any) {..}`, and there is no need for `ICanBeDisposable` - you should just use `any` in that case.

**Comment by makinggoodsoftware** [comment]
My 5cts... @guryanovev @RyanCavanaugh 

The main point of discussion here is if you are not going to implement the only optional method in the interface, well then don't implement the interface.

Well, that is flawed in my opinion. Interfaces like the ones we are discussing in this thread have always existed in frameworks exposed to users. If you are creating and consuming these interfaces internally, and not distributing your code as a library, then I understand this might be completely unnecessary and I would agree with not implementing them at all.

BUT, we are a framework used by many other developers, and these interfaces have a very important function.

First they act as marker interface, https://en.wikipedia.org/wiki/Marker_interface_pattern, they help to semantically increase the self documented aspect of the application, if I see a component implementing this interface I understand that is going to be used for a particular purpose. 

They bind to your IDE helping developers search for components that implement this interface.

They tighten the contract between the user code and the framework (ag-grid in this case). If we ever change the interface definition in a future version and the user upgrades, he gets a compiler notification and can adapt the code accordingly.

So not implementing the interface is NOT an option and is bad advise in this case. We definitely want the customer to implement the interface for all the reasons above, so in this case we are deciding what we are going to do in this case, but I honestly think that this was not a good move.

**Comment by RyanCavanaugh** [comment]
To begin...

> First they act as marker interface, https://en.wikipedia.org/wiki/Marker_interface_pattern, 
> ... link ...
> **used with languages that provide run-time type information about objects**

Regarding 

> I honestly think that this was not a good move

When we scanned breaks for this in DefinitelyTyped, the *vast* majority were people who thought they were copying down the optional members of the interface, but weren't. In other words, people thought that by writing `class Bar implements IFoo`, they'd cause some change to take place in `Bar`. It didn't. The definition was wrong.

Nothing you've said here is an impediment to writing the alternate version
```ts
class Bar {
}
interface Bar extends Foo { }
```
which has the *additional clarity* that you didn't actually implement any members of the interface, on purpose.

Consider also this case
```ts
interface IDisposable {
  dispose()?: void;
}
class MyThing implements IDisposable {
  disopse() {
    // perform important work here
  }
}
```
Can it seriously be argued that this code is OK?

**Comment by talynone** [comment]
Forgive me if I'm wrong, but why is this even being discussed? Isn't this simply a question if ag-grid is going to support Typescript 2.4+. Current ag-grid does not build with the Typescript 2.4. this will be a growing problem. At a certain point angular will come bundled with a version of Typescript greater than 2.4, will ag-grid then no longer be compatible with angular? Why is this even being considered? It's like arguing if ag-grid should support Google Chrome versions a month old and newer.

**Comment by Haemoglobin** [comment]
Agree, users will not be very happy if they can't upgrade to typescript 2.4 because of their ag-grid dependency. I'm rolling back to typescript 2.3 for now but this won't be a long term option for me.

**Comment by seanlandsman** [comment]
@talynone @haemoglobin

No one is suggesting we won't do anything about this - this is just at thread discussing the issue, not saying it won't be dealt with one way or the other

**Comment by talynone** [comment]
Thanks for the clarification @seanlandsman

**Comment by davidm-public** [comment]
@Haemoglobin correct, speaking as a user.

**Comment by SamuelBeliveau** [comment]
Can we reopen the issue so we don't lose track?

**Comment by AlanCrevon** [comment]
Hi all.

Could @davidm-public 's patch be included ASAP in a fix release, please ? 

Thanks.
Alan

**Comment by seanlandsman** [comment]
We've made changes to the codebase to accommodate 2.4 - this will be released at the end of next week, so the above PR (although appreciated) won't be pulled in

btw - although I've not tried this - does the ts skipLibCheck option help bypass this problem temporarily?

**Comment by TheTFo** [comment]
Is there any temporary workaround for this?

**Comment by ALFRED-Guillaume** [comment]
Hi @TheTFo,

@davidm-public solution work for me !

**Comment by seanlandsman** [comment]
@TheTFo I'd suggest try either skipLibCheck (although I've not tried this),  or @davidm-public patch

**Comment by bobchyko** [comment]
@seanlandsman just FYI, skipLibCheck does not appear to get around this error.

**Comment by seanlandsman** [comment]
@bobchyko @TheTFo @davidm-public @AlanCrevon @timfogarty-deluxe @guryanovev 

The latest release of ag-grid should play nice with ts 2.4 - please raise a new issue if this is not the case for you

thanks

**Comment by isc30** [comment]
Usually this error is found when intersecting full optional types (aka object with only optional properties).

Sometimes when writing generic library code, **this is something you want to do, even if the intersection results in a full optional type too**.

Normal TS intersections won't let you intersect weak types, but you can implement the intersection yourself:

```ts
export type WeakIntersect<T, U> = Record<string, never> extends T
  ? Record<string, never> extends U
    ? T & U // fallback to compiler check for weak types
    : U
  : Record<string, never> extends U
    ? T
    : T & U
```

```ts
FullyOptional1 & FullyOptional2 // error
WeakIntersect<FullyOptional1, FullyOptional2> // ok
```

It is also possible to avoid the error when using `extends` on a weak type:

```ts
export type AllowWeakType<T> = Record<string, never> extends T ? any : T
```

```ts
T extends FullyOptional // error
T extends AllowWeakType<FullyOptional> // ok
```
