### ISSUE TITLE
Absolute positioning of grid cells

### ISSUE THREAD

**Issue by bhalperin** [ceolter/ag-grid#1799]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I suspect that Chrome browser continuously busy recalculating because all the grid elements are positioned absolute. The symptom is that I can't change any styling in Chrome Devtools for experimenting with the grid.

**Expected behavior**
It seems inefficient and I'm asking why it is designed this way.

**Minimal reproduction of the problem with instructions**
Simply open Chrome Devtools, select an element inside the grid (e.g. cell) and try to change it's style by e.g. overriding the default cell color.

**What is the motivation / use case for changing the behavior?**
Efficiency. Memory usage. Customizing.

**Please tell us about your environment:**
Windows 10. VS Code.

* **ag-Grid version:** 12.0.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36

* **Language:** TypeScript 2.4.1

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid we cannot accept this as a bug... There are many ways to configure the cell styling of the grid as explained in the docs.. 

https://www.ag-grid.com/javascript-grid-cell-styling

We are not going to change the way the grid positions elements absolutely, that would require a rework from the ground up and we don't think is necessary to be honest.

It is unfortunate that absolute positioning prevents you from changing some of the style on the fly, but the other side of the coin is that because we do absolute positioning, there are many other features that we can offer.

**Comment by bhalperin** [comment]
Hi,

Thanks for your prompt reply. I was simply asking maybe there is an inefficiency issue you are not aware of. It's indeed unfortunate that I can't change the styles on the fly - an extremely helpful tool to experiment with styles during development.
