### ISSUE TITLE
Allow delete & update of rows in infinite scroll

### ISSUE THREAD

**Issue by ceolter** [ceolter/ag-grid#193]
http://www.angulargrid.com/forum/showthread.php?tid=2257

**Comment by crowmagnumb** [comment]
Would love to see this as well.

**Comment by otake1977** [comment]
+1 
I need the same row removal api versus refreshing the whole grid when user deletes a row.

**Comment by mistercz** [comment]
+1

**Comment by poornerd** [comment]
+1

**Comment by scotthovestadt** [comment]
+1

**Comment by pengx17** [comment]
+1 
Please shiptit!

**Comment by jenas-zhang** [comment]
+1

**Comment by jackyjieliu** [comment]
+1

**Comment by mashaly100200** [comment]
+1

**Comment by ceolter** [comment]
if only i could get £500 for every plus one!!!! anyway, updatable rowsets, it is on the forefront of my mind.

**Comment by diptesh-patil** [comment]
+1
I too need this feature badly..

**Comment by oh-wo** [comment]
+1

**Comment by BevanR** [comment]
👍  (+1)

**Comment by meganke** [comment]
+1

**Comment by juanotto** [comment]
+1

**Comment by BevanR** [comment]
Any update on this @ceolter?

**Comment by ceolter** [comment]
a particular customer has said they would pay for me to implement this, so it bumps it up the stack. i expect to start developing it in august.

**Comment by ceolter** [comment]
because i'm going on holidays for two weeks!!!! it's on my list for when i get back form my hols.

**Comment by BevanR** [comment]
api.insertRow(rowData, index)
api.deleteRow(index)

**Comment by BevanR** [comment]
This issue's title is currently "Allow delete & update of rows in infinite scroll".  However we already have [`api.refreshRows(rowNodes)` to update multiple existing rows](https://www.ag-grid.com/javascript-grid-refresh/index.php).

Should the title of this issue be "_API functions to add/remove rows, even virtual paging_"?

We propose adding;

- `api.insertRow(rowData, index)` to add a new row at `index`  
  Existing rows at and greater than `index` get bumped down (incremented by one).
- `api.removeRow(index)` to remove the row at `index`  
  Existing rows after index get bumped up (decremented by one)

We've used `remove` instead of `delete` to avoid edge cases or implementation details where the JavaScript `delete` might have been useful but conflicts.

### Stretch goal ideas

Roughly in order of priority;

2. Should ag-Grid emit events for these?  E.g. `rowInserted`, `beforeRowInserted`, `afterRowInserted`, `rowRemoved`, `beforeRowRemoved` and `afterRowRemoved`.  
  This would allow the developer using ag-Grid to add and remove classes during these events to, for example, facilitate animation.
4. And/or perhaps ag-Grid can add such classes automatically; this would be especially useful when inserting/deleting _multiple_ rows (see next idea).  E.g. `ag-row-inserting`, `ag-row-removing`
  Otherwise debouncing multiple calls to `insertRow`/`removeRow` could become challenging.
1. We have suggested singular methods, but perhaps they should be plural?  Or both?

**Comment by ceolter** [comment]
@BevanR thanks for the items. i plan on getting this in next week.

**Comment by ceolter** [comment]
@BevanR what would the css class & animations look like?

the adding / removing of rows would be done in one JavaScript turn, so there css classes will be removed again by the time the time the browser gets to redraw the dom. are you talking about rows moving? (eg rows animate by sliding down when an insert happens)

**Comment by BevanR** [comment]
1. Row sliding upon insert/delete would be a _very_ nice feature.  Otherwise the addition/deletion will cause jumping/jarring.  However it might be very challenging with virtual scrolling
1. It appears that as long as the class is removed in the next turn/cycle after DOM is modified, then the classes are still useful for CSS-based animations.  E.g. https://jsfiddle.net/o2apnLpu/8/ 
1. Or even in the same JavaScript cycle with a small hack.  E.g. https://jsfiddle.net/szhfwcoh/8/
1. Indeed, JavaScript events are more useful than classes; if we only get one; JavaScript events please. :)

**Comment by ceolter** [comment]
i've just finished this. it will be in the next release. planned for the next day or two.

inserting rows was easy, it's done by index.

deleting rows is hard - deleting by index gets mixed up with server side sorting and deleting. so instead i've opted for the client (ie you) to delete on the server side, then the grid has API's to refresh the cache, so it will reload rows after the delete.

**Comment by BevanR** [comment]
Thanks @coelter!

Is there a dev build or nightly build we can try it out with?

Do I correctly understand the problem with `removeRow()` as follows? If the parameter is a;

1. row index, the client (consuming ag-Grid) is likely to get confused (buggy) when the user (human) sorts or filters the data.
1. row node or the row's unique identifier (server-side ID), if the row is not in the viewport, ag-Grid can't tell whether the row is above or below the viewport

Would simple cache invalidation cause a redraw or UI flash?

Perhaps;

1. This is the client's problem.  Can we make that clear in the documentation?  
  (Thanks for trying to keep the API easy to use and fool-proof! 👍  )
1. 
    1. 
        - Does ag-Grid know the nodes or unique idenrifers of all rows preceding the current viewport? E.g. if the user scrolled past them?
        - Can ag-Grid use that to know whether row is above or below the viewport?
    1. In our implementations of ag-Grid with virtual pagination we have had to store a map of the selected state of all rows so that the selected state of each row persists beyond the current viewport, and can be restored when the selected row returns into the viewport, or when the user executes an action the selected rows.  If ag-Grid stored such a map of the unique identifier (and selected state?), would it then be able to determine where a row is by row node or unique identifier?

**Comment by ceolter** [comment]
@BevanR 

```Is there a dev build or nightly build we can try it out with?```
=> I did a full release on Friday last week including this feature.

```Would simple cache invalidation cause a redraw or UI flash?```
=> depends on whether you refresh (just redraw once data loads) or purge (data removed, wait for load, then redraw, so blank rows while loading) the cache.

```Does ag-Grid know the nodes or unique idenrifers of all rows preceding the current viewport?```
=> No it doesn't, except for selected. One improvement I had in last Fridays release is the grid now keeps track of selected rows. So the rows stay selected as the scroll moves up / down, but also between server side sorts and filters. This is done using with your client providing id's for the rows.

**Comment by BevanR** [comment]
1. Cool!  Is there a way we can be notified when there are a new versions?
1. Ahah!  Now that we've had a toy with this, `refreshVirtualPageCache()` is easier and better than the new insert method, barring a possible bug/improvement noted in https://github.com/ceolter/ag-grid-docs/pull/41
1. Awesome!  Initial integration attempts suggest this will let us delete a lot of code!

**Comment by ceolter** [comment]
@BevanR 
1. join my mail dist list. details on main doc page. follow me on twitter.
2. great.
3. great again!

**Comment by BevanR** [comment]
Done.  Thanks!  One more followup; https://github.com/ceolter/ag-grid-docs/pull/44
