### ISSUE TITLE
Undesired background gap

### ISSUE THREAD

**Issue by dereklin** [ceolter/ag-grid#229]
Here is my plunker: http://plnkr.co/edit/eucZEX6bg57lREyXtYVj?p=preview
When it's first loaded, there is a background gap between the last row and the bottom border of the grid.

I have to do this to remove it:

```
.ag-body-viewport {
    margin-bottom: -3px;
}
```

Is this due to the height calculation in pixels due to box-sizing?

**Comment by ceolter** [comment]
yes i think it is due to something like you say. i've noticed this before, but don't know under what circumstance it happens. eg my test drive and examples (i just took a quick look at the 'getting started, loading rows' example) all work fine. yet the larger example (http://localhost/example-data-grid/index.php) and your plunker show it happening. as it's a very small detail, i don't have fixing it very far up my list.  and nobody has mentioned it to me until now.

**Comment by ceolter** [comment]
not happening in latest.
