### ISSUE TITLE
proposal: remove site code from repo to make it smaller

### ISSUE THREAD

**Issue by nonmanifold** [ceolter/ag-grid#25]
move site code to another repo.

**Comment by ceolter** [comment]
hi nonmanifold, why is the github size an issue? if your using the grid then you only need the javascript file that is the result of the build? am i missing something?

**Comment by nonmanifold** [comment]
if someone adds your package as bower dependency, a snapshot of package repo is downloaded, 
I'm currently working on Pull request which will contain metadata files to be used by Bower and NPM, I'll add site to ignores so it won't be downloaded to developer's pc when package is referenced as a dependency.
Take a look at bootstrap repo: https://github.com/twbs/bootstrap  they've got a folder called 'docs' which contain only docs, but not the blog posts about package.

**Comment by ceolter** [comment]
Brill, thank you very much, pull request merged.

**Comment by thorn0** [comment]
Also have a look at the `bower.json` spec: https://github.com/bower/bower.json-spec
* The `version` field isn't used. It's better to remove it than to update it aimlessly with every version.
* The `main` field should point to a self-sufficient built file. `website\dist\angularGrid-latest.js` is a better value for it. Solutions like [grunt-bower-task](https://github.com/yatskevich/grunt-bower-task) rely on this convention.

**Comment by thorn0** [comment]
Besides `website\dist\angularGrid-latest.js`, `main` should also include CSS and all the other files that are needed for the library to work properly.

**Comment by thorn0** [comment]
And also the tags in the repo are not (semver)[http://semver.org/], that's why Bower doesn't recognize them. Please fix this.

**Comment by ceolter** [comment]
Hi @thorn0, the angularGrid-latest.js does include everything, including
the css. See the examples, this is all that's referenced!

On 7 April 2015 at 22:31, thorn0 <notifications@github.com> wrote:

> Besides website\dist\angularGrid-latest.js, main should also include CSS
> and all the other files that are needed for the library to work properly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/25#issuecomment-90738232>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by thorn0** [comment]
Ah, great. It means it's the only file that needs to be specified in `main`.

**Comment by davidgeary** [comment]
I agree with @thorn0 - I've just installed the package via bower and cannot see any reason why I need to have the complete website code just to use the grid in my project.  It then took me a while to realise that the distribution files were buried in the website's dist folder (I saw the reference to it in the [readme](https://github.com/ceolter/angular-grid/blob/master/README.md), but assumed that it was referring to the live website at http://www.angulargrid.com/, not the `website` folder in the source).

If someone wants to update the website, they would fork the project in Github, so can it not be removed from the bower package and replaced with just the `dist` folder?

I would also suggest that you only need to include the latest version in the package (which would allow it to be named simply `angularGrid.js`, rather than `angularGrid-latest.js`).  AFAIK, bower is pulling the files from the git repository, so as long as each release is tagged correctly, people will still be able to install older versions by specifying the version they want when installing via the bower command line.

**Comment by ceolter** [comment]
Thanks for the feedback. Will fix it up.

The website is in got because its mostly documentation, and its a way to
keep the docs in sync with the code. But I agree, it shouldn't be in the
bower dist.

**Comment by tannerlinsley** [comment]
We're currently trying to decide where to put it, but it will probably be separate in the next release :)

**Comment by dougpix** [comment]
+1

I'm trying to include this using jspm, and regardless of endpoint (github, npm, or bower) it would be great if the latest in dist was specified in main instead of needing to do an override!

**Comment by thorn0** [comment]
Bower ignores the `version` field in `bower.json` and uses git tags instead. The tags must be valid semver versions. For example: `1.4.1` is semver, `1.4` isn't. Please keep the tags semver-compliant in order for Bower to work with this library.

**Comment by ceolter** [comment]
Thanks for raising. Will fix when back from hols.

**Comment by ceolter** [comment]
site code now in separate repo
