### ISSUE TITLE
GridPanel.getWidthForSizeColsToFit() bug

### ISSUE THREAD

**Issue by greglockwood** [ceolter/ag-grid#268]
Here is the way I am currently using the grid in some places:
- I am using pagination with a datasource
- I am setting a height big enough for the `(pageSize + 2) * rowHeight` (the `+ 2` is for the header and footer rows) so there is no need for actual scrollbars.
- Because the scrollbars are irrelevant, I am hiding them in CSS by using `overflow: hidden`.
- I am using `api.sizeColumnsToFit()` to get the columns to fill the available width inside the `ready` callback.

However, because your check in [`GridPanel.prototype.getWidthForSizeColsToFit()` line 129](https://github.com/ceolter/angular-grid/blob/master/src/js/gridPanel/gridPanel.js#L129) is evaluating to `true`, the width to consume is reduced by the scrollbar width, even though there will be no scrollbars visible to consider.

The strange thing is why that check is returning true. The check is `this.eBodyViewport.clientHeight < this.eBodyViewport.scrollHeight`. When I debugged it, the `scrollHeight` was 20 for some reason, and the `clientHeight` was 0. Interestingly, the difference of 20 is less than the size of any row, header or footer. Perhaps that could be the key to making a more robust check?

In case you were wondering, I couldn't use the `dontUseScrolls` option because I am doing pagination, and you can't do pagination when using `dontUseScrolls`.

**Comment by ceolter** [comment]
my guess is 20 is the width of a scrollbar?

why are you hiding the scrolls? if your grid is the right height and you use sizeColsToFit, then the grid will be the right size, the scrolls only appear when the grid can't fit the data???

**Comment by greglockwood** [comment]
You might well be right about 20 being the width of the scrollbar.

However, I found another odd thing: when I took off my `overflow: hidden` CSS rule, the scrollbar showed up (because I think I am not allowing enough height for the borders or something*), but the last column was still 20px away (a guess) from the scrollbar.

Here is a screenshot from Chrome latest:



* This was why I hid the scrollbar in the first place. Saved me worrying about a few pixels of overflow due to borders.

**Comment by ceolter** [comment]
sorry if i asked this before (so many questions and threads i'm involved with, i might be getting them mixed up), but why are you trying to hide the scrollbar? the grid should only show the scroll if it is needed, so if you sizeColsToFit() at the right time (after data is loaded, so vertical scroll decision is made), then you shouldn't have to manually make the horizontal scroll go away???

**Comment by andrea-vega** [comment]
I am not sure if this is what @greglockwood is talking about, but when I call sizeColumnsToFit(), the grid causes a horizontal scrollbar because it takes slightly too much width to size the columns with.  If I put a $timeout of about 200 ms, the grid renders fine.  It miscalculates the grid's container size before it renders, causing scrollbars to appear.

**Comment by ceolter** [comment]
@andrea-vega you are calling sizeColumnsToFit() before the data is loaded into the grid, hence the grid is not away for the scrollbar (yet). your workaround is fine, or you should just call 'sizeColumnsToFit()' after you load new data into the grid (might need to put into a timeout with 0 millis).

**Comment by ElPernotador** [comment]
I solve this issue changing the function like
            GridPanel.prototype.getWidthForSizeColsToFit = function () {
                var availableWidth = this.eBody.clientWidth;
                var scrollShowing = this.eBodyViewport.clientHeight < this.eBody.clientHeight
                if (scrollShowing) {
                    availableWidth -= this.scrollWidth;
                }
                return availableWidth;
            };
the problem is calculating scrollShowing

**Comment by ceolter** [comment]
i need to set some time aside to look into this :( . . . . . i put about 20min into it just now, but i started getting a headache!!!

**Comment by ElPernotador** [comment]
One aditional detail, i need to call to sizeColumnsToFit like this :(
if timeout is lees 500ms, fail

      scope.gridOptions.onReady = () ->
        $timeout () ->
          scope.gridOptions.api.sizeColumnsToFit()
        , 500

**Comment by ceolter** [comment]
this is an old issue, i'm not sure if it is still valid with all the code chances since. if still valid, please reopen the issue.

**Comment by Pitmov** [comment]
Hi, this issue is still reproducible in IE 11. We have this strange 20px gap in ag-grid only in this browser. I change source code with El pernotador example and ag-grid start working ok in IE 11. 
So adding this condition fixed everything for me:
`var scrollShowing = this.eBodyViewport.clientHeight < this.eBody.clientHeight
if (scrollShowing) {
availableWidth -= this.scrollWidth;
}`

Also I use globalEventListener from gridColumnsApi to use sizeColumnsToFit function only on 'gridSizeChanged' event - it helps to hide unneeded scrollbars. Of course I have other listeners that execute sizeColumnsToFit when it needed for me.

So issue still reproducible on IE 11, ag-grid version 10.1, OS - Win 7.
