### ISSUE TITLE
ensureIndexVisible() function to scroll that row to the top

### ISSUE THREAD

**Issue by Fangmingdu** [ceolter/ag-grid#278]
Right now the ensureIndexVisible() function only makes the row visible. It would be better if it makes to be the top row.

Thanks!

**Comment by ceolter** [comment]
thanks! will add to my list n' think about it - might have to make it work a little different, maybe two api calls, as my thinking was 'if its already visible, dont do anything' . . . maybe a 'scrollToTop' function as well as 'ensureVisible' ....

**Comment by alxndrmlr** [comment]
+1 having an option to ensureIndexVisible where its at the top of the table would be great!

**Comment by ceolter** [comment]
this is already supported, just scroll the grid to the bottom (scroll to the last index), then scroll back to the top.

**Comment by dereklin** [comment]
There should be an option to not scroll the grid when the row is already visible in the viewport.  Right now, ensureIndexVisible scrolls the grid even when the row is visible.

**Comment by carvalhosedu** [comment]
**here is the solution to set the row position on the grid.**
https://www.ag-grid.com/archive/21.0.0/javascript-grid-api/#scrolling

**more specifically:**
**ensureIndexVisible(index, position)** : Ensures the row index is visible by vertically scrolling the grid. The valid values for positions are {'top', 'middle', 'bottom', undefined/null}. If top, middle or bottom, the grid will scroll the row to place the row at top, middle or bottom. If undefined or null then grid will do the minimum scrolling to show the row, ie if grid needs to scroll up then it will scroll so that the row is at the top, if the grid needs to scroll down then it will scroll so that the row is at the bottom, if the row is already in view then the grid will do nothing.
-- | --
