### ISSUE TITLE
api.setColumnState(state) not render cell group

### ISSUE THREAD

**Issue by loongdefect** [ceolter/ag-grid#293]
When call api.setColumnState grid not render cell Group

**Comment by ceolter** [comment]
Is this happening on the demo page for you? What you mean by cell group?

**Comment by loongdefect** [comment]
Hi ceolter,
this is demo
http://plnkr.co/edit/VYOmzXjAcz9ARqzjWJR6?p=preview

**Comment by ceolter** [comment]
thanks for raising. i see what you mean. i'll need to look into it and get back to you.

**Comment by ceolter** [comment]
it's because your are pivoting by an imaginary column. if you stick this onto the end of your columns, it will work:
{headerName: "field1", field: "field1", hide: true}

not sure if this is a bug, or a feature, i'll have to think about it. it's not simple to 'fix' as the setColumnState() sets the state, including pivoting. maybe i include a flag 'suppressPivot' so it doesn't overwrite pivot info. or can just say it doesn't support the pivot by non-columns.

**Comment by ceolter** [comment]
pivoting and grouping has undergone a lot of changes since this issue. if this is still an issue, please reopen.
