### ISSUE TITLE
Custom framework cell renderer causing weird behavior

### ISSUE THREAD

**Issue by gnbaron** [ceolter/ag-grid#4705]
We are trying to validate the ag-grid usage in my company's app so we can acquire the enterprise version but there are some weird bugs we'd like to understand before.

**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Framework: react

Example: https://plnkr.co/edit/JFmok4c9wckYEQCr

**Current behavior**
When using a custom cell renderer through `cellRendererFramework` that fires some sort of action which changes the row data, the grid resizes all columns again.

**Expected behavior**
The grid should keep the columns state achieved by calling `api.sizeColumnsToFit()` on `onFirstDataRendered` event.

**Please tell us about your environment:**
OSX

* **AG Grid version:** 25.3.0

* **Browser:**
All

* **Language:**
All

**Comment by kiril-matev** [comment]
Hi @gnbaron 

We've looked into this and concluded it's not a bug.

This behavior is caused by the fact you're changing the column definitions each time the React render() function is called. As the Column Definitions contain an inline function for the Cell Renderer, AG Grid thinks a new Cell Renderer is configured (new instance of the function) and hence is reacting to changed columns.

Please address this by replacing the Cell Renderer with an out-of-line Cell Renderer, as shown in the sample below:
https://plnkr.co/edit/G3TZkEm0u0oN8lVH

Thank you for bringing this up with us.
