### ISSUE TITLE
`suppressCellSelection` should have the functional effect suggested by the docs, rather than a purely visual effect

### ISSUE THREAD

**Issue by MaximSagan** [ceolter/ag-grid#4746]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Setting `suppressCellSelection` to `true`only hides cell selection styling, but has no functional effect. Cells can still be selected (focused) using the keyboard (tab) - albeit the user will not know where the current active element is. (It's hard to imagine that this is anybody's desired behavior.)

I have prepared [a plnkr that illustrates the issue](https://plnkr.co/edit/Dh85VsYla6AYBMZV). I am listening to "focusin" from the body element and printing the contents of the currently selected element. We can clearly see that despite `suppressCellSelection` being set to `true`, all cells are still receiving (invisible) focus, making keyboard navigation extremely difficult.

**Expected behavior**
According to [the documentation](https://www.ag-grid.com/javascript-data-grid/keyboard-navigation/#suppress-cell-selection),
 
> If you want keyboard navigation turned off, then set `suppressCellSelection=true` in the gridOptions.

This suggests to me that I should not be able to tab through any grid cells, i.e. If I'm focused on an DOM element that precedes the grid, I should not have to tab through ever single cell to get to an element that follows the grid (which I currently have to, as I demonstrate in [my linked example](https://plnkr.co/edit/Dh85VsYla6AYBMZV)).

**Code reference**
We can confirm that `suppressCellSelection` only has a visual effect by observing the only place in the codebase where the property is used, and that is used only to add/remove a CSS class:

https://github.com/ag-grid/ag-grid/blob/b4f2a56a03033e4b40a93c494b5c40d5c722ea8d/community-modules/core/src/ts/rendering/cell/cellCtrl.ts#L1002-L1004

**Comment by MaximSagan** [comment]
@kiril-matev
Thanks for your quick feedback.

My concern however is that it seems that you're suggesting that the issue is purely that the documentation is wrong, so all we need to do is fix the documentation in line with `suppressCellSelection=true`'s actual behavior (i.e. simply removing visual indication that a cell is focused, while still allowing the cell to be silently focused).

But there a couple issues here:
1. Even after updating the docs, the name of the property would still be `suppressCellSelection`, which suggests that selection (functional selection) would actually be suppresed.
2.  Do we honestly think the actual behavior of  `suppressCellSelection=true` (i.e. simply removing visual indication that a cell is focused, while still allowing the cell to be silently focused) is desirable to anyone? I have trouble believing it would be.

**Comment by kiril-matev** [comment]
Hi @MaximSagan,

Thanks for your response.

I think there's an important distinction to be made here - selection and focus are different interactions offered by AG Grid. However the current documentation makes it look like by suppressing cell selection you can disable cell focus. As you've demonstrated, this isn't the case. This is what we need to address in our documentation.

Thank you for raising the second point because I believe it's quite important:

The behavior provided by setting suppressCellSelection:true doesn't have an effect on selection because a cell cannot be selected unless you have set enableRangeSelection: true anyway. As you've pointed out, the logic behind setting suppressCellSelection:true only disables cell focus styling and needs to be enhanced as follows:
1/ disable cell focus via mouse click or keyboard navigation
2/ rename property to more clearly communicate its relationship to cell focus and not cell selection

I have entered a backlog item for this work:
**AG-5953 [Keyboard Navigation] Allow setting suppressCellSelection:true to disable cell keyboard focus and rename it to reflect its effect on cell focus, not selection**

I understand that you'd like to disable the focusing of cells and would like to TAB through the grid as a single element inside of TAB through its individual cells. We have provided an example which lets you achieve this - disable cell focus, allowing you to TAB through the grid as a single element. 

Thanks again for bringing this up with us.

**Comment by MaximSagan** [comment]
Hi @kiril-matev,

It seems that the problem is now well understood. Thanks again for being so responsive!
