### ISSUE TITLE
Unnecessary horizontal scrollbar when grid height is set via binding

### ISSUE THREAD

**Issue by jonrimmer** [ceolter/ag-grid#476]
When the height of the grid is restricted via an ng-style binding such that it causes vertical scrolling, the grid responds to the change in size, but displays an unnecessary horizontal scrollbar:

http://plnkr.co/edit/mTzm2OkrqDygW0mvs7zc?p=preview

**Comment by ceolter** [comment]
this is not a bug. the grid is sizing itself to the containing div size. the problem is that the AngularJS is not setting the height of the div until after the digest cycle has run it's course, by which time the grid is already sized.

to work around this, change your toggle function to the below. it will get the grid to lay out after the the grid is resized by angular.

```
  vm.toggleGrid = function() {
    vm.showGrid = !vm.showGrid;
    setTimout( function(){ vm.grid.api.doLayout(); }, 0);
  };
```
