### ISSUE TITLE
filterModel returns CSV list without escaping commas

### ISSUE THREAD

**Issue by SetTrend** [ceolter/ag-grid#515]
The `ag-grid` default `'set'` filter implementation returns a CSV list of all the values being checked in the column filter checkbox list.

However, if any of these values contains a *comma* by itself, then this item is not getting escaped by surrounding it with quotes. So any parser is going to misinterpret the CSV list.

This looks like a bug to me.

When returning a CSV list, `ag-grid` should comply to [RFC 4180](https://tools.ietf.org/html/rfc4180#page-).

**Comment by S-YOU** [comment]
According to filtering example - http://www.ag-grid.com/angular-grid-filtering/index.php
It looks like you pass array of string for `values` instead of comma separated string.

I tried to change 
- `var irishAthletes = ['Michael Phelps', ....` to 
- `var irishAthletes = ['Michael, Phelps', ... ` and changed underlying example data to `Michael, Phelps`, It seems to be working here.

**Comment by SetTrend** [comment]
Absolutely. Sorry, I didn't JSON.Stringify() again here. My mistake.
