### ISSUE TITLE
Javascript error on runtime - unable to instantiate module

### ISSUE THREAD

**Issue by JeffMichelson** [ceolter/ag-grid#517]
Using Angular 1.4.  Webpack.  ng-strict-di="off".  Get the following error at runtime:

Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module function e(e,t){var i;if("string"==typeof e){if(i=document.querySelector(e),!i)return void console.warn("WARNING - was not able to find element "+e+" in the DOM, Angular Grid initialisation aborted.")}else i=e;new ag.grid.Grid(i,t)} due to:
Error: [$injector:unpr] Unknown provider: e

Apparently the parameter "element" is not being explicitly annotated.

**Comment by ceolter** [comment]
this doesn't make sense. the error "was not able to find element" is printed from the angularGridGlobalFunction method. this method is not called by anywhere in the ag-Grid code, it is intended to be called when you want to use the grid outside of AngularJS.

so i'm thinking this is not an issue with the grid, rather something you are doing wrong on your end???

**Comment by JeffMichelson** [comment]
Hm.  The problem was called when the template reference:

<div ag-grid="vm.gridoptions"  class="ag-blue" style="height: 100%;"></div>

did not match the name in the controller: 

this.gridOptions = gridOptions;

But I've made changes in the controller code subsequent to resolving the problem and now I can't seem to regenerate that error.  So, please close this issue and I'll let you know if the problem recurs.

Thanks.

**Comment by wendellm** [comment]
Well I have recreated this error by accident I confess and I am not getting rid of it. I'm getting this same exact message. I am using webpack but my setup is as described by the webpack and ag-grid documentation and it should work but ;
Error: [$injector:modulerr] Failed to instantiate module cs-app due to:
[$injector:modulerr] Failed to instantiate module function e(e,t){var i;if("string"==typeof e){if(i=document.querySelector(e),!i)return void console.warn("WARNING - was not able to find element "+e+" in the DOM, ag-Grid initialisation aborted.")}else i=e;new ag.grid.Grid(i,t)} due to:
[$injector:unpr] Unknown provider: e

is spoiling it :) perhaps you can reopen this issue

**Comment by ceolter** [comment]
it's open, but i don't use webpack, so it's not something easy for me to look into.

**Comment by wendellm** [comment]
I am going to turn one of your examples into one with webpack so we can isolate the problem. I will put it up on github and ask the webpack team to have a look at it to. Thanks for reacting so quick and for building and sharing such an awesome product.

**Comment by chiptus** [comment]
Hi, I'm using webpack as well, I had this problem at first.
The solution is instead of doing:
    angular.module("mymodule",[require("ag-grid")])
do the following:
    require("ag-grid");
    angular.module("mymodule",["agGrid"])

I guess what happens is that require("ag-grid") exposes agGrid as a global
module and then you can use it. Maybe in the future nial can add support
for webpack, but for now this is working great.

**Comment by ceolter** [comment]
thanks @chiptus, does that mean we can close this issue?

**Comment by wendellm** [comment]
hey thanks that worked @chiptus not flawlessly though but I'll open other issues for that. @ceolter You can close the issue again since it now has definite workaround. Thanks
