### ISSUE TITLE
Columns percentage width is not taking in account in cells

### ISSUE THREAD

**Issue by franciscopuyo** [ceolter/ag-grid#520]
If you set a percentage as a column width it, it is applied to the header but in cells the library adds "px" after and breaks the element custom style.

in src/ts/rendering/renderedCells.ts
```
+  if (this.column.actualWidth.slice(-1) == '%') {
+        this.vGridCell.addStyles({width: this.column.actualWidth});
+ } else {
       this.vGridCell.addStyles({width: this.column.actualWidth + "px"});
+ }
```
I don't know if it works with resizing, perhaps it should disable it too but this would solve it and they are only 3 lines that perhaps would help somebody (me for example)

**Comment by ceolter** [comment]
width is meant to be a number only, no %. this is because of, as you guess, the resizing. i want complete control of the pixel widths for the cells. also am sure it would cause issues for pinning or other stuff going forward as i enhance the features.

any reason you cannot use api.sizeColumnsToFit()???

in the future, i plan to allow 'weights' on the columns (will work similar to %), but that's still in my plan.

**Comment by juanmav** [comment]
@ceolter api.sizeColumnsToFit() doesn't get a smooth transition when you resize the grid.

**Comment by ceolter** [comment]
A 'stretch' animation while resizing??? Or they adjust after the resize?

**Comment by SatyabratKumarSingh** [comment]
They adjust after resizing and there is a delay on that. In my case users have been complaining as initially the grid loads and then does sizeColumnsToFit. Any other way of achieving it?

**Comment by juanchib** [comment]
Hi , any news on the plan to allow 'weights' on the columns ?
