### ISSUE TITLE
Clipped Horizontal Scrollbar

### ISSUE THREAD

**Issue by highvoltz** [ceolter/ag-grid#5283]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
https://plnkr.co/edit/ut8NwI1hSAYbcEEa

**Current behavior**
When using a webkit browser (Chrome/Edge), the top of the horizontal scrollbar gets clipped if custom CSS sets scrollbar height more than the vertical scrollbar width.
In the plunker above, if you scroll all the way to the bottom, you can see the top of the clipped scrollbar inside of the grid

**Expected behavior**
AG Grid's horizontal scrollbar can be a different size than the vertical scrollbar

**Please tell us about your environment:**
N/A

* **AG Grid version:** X.X.X
27.3.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

We are aware of this feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

To allow GitHub users to provide feedback we are going to flag this ticket as community-engaged, which means that concerns and/or opinions around this feature request are welcomed and you can expect as well to hear back from us with updates.

We have linked the feature request in our system to this ticket so they will be taken into consideration when is selected for development.

Note that because we prioritize enterprise customer support, it might take us some time to update this ticket.

This is the reference and summary of the relevant issue:

___
AG-1366
Allow customising scrollbars even in FF

**Comment by highvoltz** [comment]
Sorry, it's been awhile since I logged in. This is bug, not a feature request. I checked out the code and AG-grid wrongly assumes the horizontal scrollbar will be same width as the vertical scrollbar. The bug happens when they're not the same width.
