### ISSUE TITLE
v28 Grouping by a column does not prevent the autoGroupColumn from re-grouping

### ISSUE THREAD

**Issue by wjaspers** [ceolter/ag-grid#5376]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
We do have Zendesk support.

**Providing a Reproducible Scenario**
Plunker: https://plnkr.co/edit/pSyo9GVtxhGAeElg?open=app%2Fapp.component.ts
Load the plunker, then click on the "Group" column menu.
Note the unexpected "Group by Group" option in the context menu.

**Current behavior**
When opening the auto group column's context menu, the "Group by ..." option is shown even when we are already grouping.

**Expected behavior**
When opening the auto group column's context menu, the "Group by ..." option is NOT shown.

**Please tell us about your environment:**

* **AG Grid version:** 28.0.0

* **Browser:** all

* **Language:** all
![Screenshot from 2022-07-18 11-57-58](https://user-images.githubusercontent.com/598148/179564384-d0e0e92f-f4c4-40e8-b842-3fcaaed778e8.png)

**Comment by kiril-matev** [comment]
Hi @wjaspers!

Thank you for bringing this up.

This is expected behavior because the defaultColDef settings apply to all columns including the auto-group column (and pivot columns for that matter). This is why since you have enableRowGroup=true in the defaultColDef, this means the auto-grouped column can also be grouped, which is indicated in its column menu.

In order to prevent the auto-group column from being grouped (while allowing all other columns to be grouped), please set enableRowGroup=false in the autoGroupColumnDef.

Please see this below:
1. Open
https://plnkr.co/edit/5eh8M1J5gK0msR23?open=main.js
2. Open GROUP column menu
**Actual & Expected**: Column menu doesn't show a GROUP BY GROUP item

Please use the approach above to resolve this.

Thanks for raising this and for using AG Grid!
