### ISSUE TITLE
show columns renders slowly. 

### ISSUE THREAD

**Issue by ajgraham671** [ceolter/ag-grid#553]
Hello! I am currently having issues with the show/hideColumns -- more-so the show feature. I'm referencing the show/hide example found on the documentation page. I have AngularCompileRows turned on and about 90% of my columns (28 columns in total with 8 rows) have custom cellRenderers. I am able to hide the columns with no problems and I can render a portion of the columns (18) with little to no wait time. However, when I hide all the columns and then try to show all 28 columns, it can take quite a while to show up or I get the "this script is taking too long" error. Any ideas on how I can speed up this process? I know using AngularCompileRows can slow things down a bit but I didnt expect to get the "this script is taking too long" error with just eight rows. BTW, I've removed all cell renderers and tried to show the columns. Same outcome minus the "this script is taking too long" error. 

Other than this, I love the library and its ease of use. Great work!

**Comment by ceolter** [comment]
Hi. Thanks for your compliments. 😊

As this is a question, it should be on the forum, issues are for items that need fixing in the grid. So will close.

This sounds like a gerenal 'grid taking to long' question. Usually this is due to grid height not set and the grid is trying to render far more rows than are visible in your browser. This can happen if no height is set on the grid. Please can you verify this? Make sure height is set on the grids div. If using % height, please test with pixels as % can fail based on your parents CSS layout.

PS if you can move to the forum please. You will prob get help there from others as that's where the community hangs out. I am travelling right now so don't get online often.

**Comment by ajgraham671** [comment]
Great! Thank you. I will move to the forum.
