### ISSUE TITLE
Filter's cellRender is getting only string value

### ISSUE THREAD

**Issue by raghav135** [ceolter/ag-grid#561]
When the column has date objects, the cellRendering of table is getting the object as date (as expected). But when we are using cell render on filter for same column, it only gets string object.

So, it is not easy to do filter cellRendering on dates.

I have created a plunker to make it easy to simulate / understand the issue.

http://plnkr.co/edit/2u0o3w7UFFuDaU1jZD3g?p=preview

**Comment by raghav135** [comment]
Same issue happens for comparator function for filter also, please see the below plunker

http://plnkr.co/edit/1ECHxH?p=preview

**Comment by ceolter** [comment]
this is because the set filter needs a string key for a value, as it stores the selected values in a map using the standard javascript object, and javascript objects use strings (only) as keys for the map. the javascript object is used for performance reasons, for large sets.

if you want to use the set filter for dates, then the easiest is to create a valueGetter and return strings for the dates. this will get the filtering working. then for the sorting, provide your own comparator that converts the strings back to dates.

or you can create your own filter for dates. you will need to build this yourself and have it so it doesn't use the javascript object.
