### ISSUE TITLE
Cannot resize columns in IE when Overlay is displayed

### ISSUE THREAD

**Issue by killyosaur** [ceolter/ag-grid#597]
This issue occurs in IE 9+. if there are no rows to show, the overlay blocks a user's ability to resize columns, the icon for resizing does not show. This issue is not present in Chrome, (have not checked any other browsers).

**Comment by ceolter** [comment]
This is because IE 9 doesn't implement the CSS spec correctly. It works in other browsers and later versions of IE.

As it's fixed in later IE (and Edge) I am slow to fix.

To get around this, you can use the property suppressNoRowsOverlay, and then if you want you can provide your own message to the user somewhere that doesn't block the grid.
