### ISSUE TITLE
Cellrenderer always firing

### ISSUE THREAD

**Issue by dvrakas** [ceolter/ag-grid#604]
Is the behavior of the cell renderer to always fire when scrolling?   I have a custom column which contains some dynamic markup  ...   When scrolling, the cellrenderer seems to always keep firing.  Is there a way to turn this behavior off.

**Comment by ceolter** [comment]
yes, it fires because of the virtual scrolling. the grid will only render the rows that are visible inside the scrollable area.

you could turn this off by setting the rowBuffer property to be something huge, any number larger than the number of rows in your grid. that way, the grid will always render all the rows, but you run the risk of having a slow grid.
