### ISSUE TITLE
Filters are not getting reset after loading new data to grid based on selected date

### ISSUE THREAD

**Issue by pacificeyes** [ceolter/ag-grid#606]
HI,
I'm using the date field as a selection criteria for populating the grid.
I want to reset the previously applied filters once the new data is about to be loaded in grid.
However, the filters are not getting removed and the menu icon for filter is showing additional values under select boxes which is very confusing in case the grid has less number of rows.
Please assist me in getting this resolved.

**Comment by pacificeyes** [comment]
The resolution of this issue will really be a great help.

**Comment by ceolter** [comment]
The default behaviour for the filters is to clear when new data is loaded. To override this, you add the property: newRowsAction: 'keep'

For example, in the test drive, "Country" and "Language" have this set, but "Game of Choice" does not. So when you set filters in these three columns, then reload the data (eg change the number of rows), then two of the three columns keep the filters, but the last gets cleared.

If you are not experiencing this, then something mush be wrong in your code? Can you provide a plunker? (otherwise i'm nothing to work on)

**Comment by MijanurR** [comment]
I have used  { cellHeight: 100, values: colname }". but still filter not getting changed.
