### ISSUE TITLE
Bulk selectAll/ selectNone on the toolPanel / agList of columns

### ISSUE THREAD

**Issue by vladimir-ivanov** [ceolter/ag-grid#639]
In our case we are dealing with 100+ dynamically generated fields,
so some people may want to do bulk select/ deselect (I personally extended it with a checkbox to selectAll/ DeselectAll)/ toggle buttons are also an option (a checkbox saves space, but adds an extra click if you want to deselectAll -> first selectAll - checked state, then deselectAll - unchecked state)

**Comment by scotthovestadt** [comment]
In my use-case, I have a selection model separate from the grid. I'm using a remote datasource and when "select all" is clicked, I may need rows selected that aren't known yet.

I don't think individually selecting rows is a good way to approach the "select all" use-case because not every grid is going to have all data loaded in.

**Comment by vladimir-ivanov** [comment]
Sorry for explaining it wrong - it is for select all/ hideall columns
rather than rows, for rows agreed, does not makes sense, agreed

**Comment by vladimir-ivanov** [comment]
columnController.hideColumns - performance when adding bulk colIds and hide = false is very slow - tested with 95 colIds - single row record takes around a minute to render.

**Comment by amit-coditas** [comment]
@vladimir-ivanov , Can you please help how you extended the column panel in toolbox? I have 100+ columns and want to lazyload them.
