### ISSUE TITLE
Agg Function with DataSource

### ISSUE THREAD

**Issue by maraisr** [ceolter/ag-grid#646]
Humour me here, but it seems you cannot aggregate with a datasource. What I mean, my data comes from a datasource,but the moment I put the `groupAggFields` property in the config, the following error occurs: `TypeError: Cannot read property 'length' of undefined` and happens at ` InMemoryRowController.prototype.recursivelyCreateAggData` at `nodes.length`.

**Comment by ceolter** [comment]
correct, you cannot do aggregation when using virtual pagination. this is by design, as if the grid doesn't have all of the data in memory (the reason why you are using virtual pagination) then it cannot aggregate.

this applies for virtual pagination, not normal paging, as normal paging will aggregate the current page.
