### ISSUE TITLE
AgChartsReact gives error "ReferenceError: changeCb is not defined" since version 6.0.0 when using Closure Compiler

### ISSUE THREAD

**Issue by armincerf** [ceolter/ag-grid#6579]
This happens since version 6.0.0 of AgChartsReact, and it only happens in production builds using code compiled by the google closure compiler (in this case via shadow-cljs, a clojurescript build tool). I have a minimal reproducable example [here](https://github.com/armincerf/ag-charts-v6-bug), just clone and run `yarn && yarn preview` which will build a production version and host it at `http://localhost:8080`.

If you go to that URL and open the console you will see the stack trace.

The code just creates a minimal AgChartsReact element with the following props
```
{options: {data: []}}
```
and it works fine if you run it in development mode (no closure optimisations, can test with `yarn dev`).

full error below:

```
react-dom.production.min.js:128 Uncaught ReferenceError: changeCb is not defined
    at f.set_visible [as visible] (eval at <anonymous> (changeDetectable.js:51:22), <anonymous>:13:25)
    at f [as constructor] (node.js:124:9)
    at new f (group.js:74:28)
    at n.S [as constructor] (chart.js:142:28)
    at new n (cartesianChart.js:102:28)
    at B.createChartInstance (agChartV2.js:354:20)
    at B.createOrUpdate (agChartV2.js:233:37)
    at B.create (agChartV2.js:128:32)
    at r.componentDidMount (agChartsReact.js:27:53)
    at pj (react-dom.production.min.js:262:217)
```

**Comment by alantreadway** [comment]
Hi @armincerf, thanks for reporting this.

On the surface, this appears to be a bug or incompatibility in the `shadow-cljs` compiler, as `changeCb` is a function parameter name that is referenced from a templated function call in the Charts codebase. I browsed the `shadow-cljs` GitHub issues and can see several similar `ReferenceError` issues closed in the past, so would guess they are still closing the gap on supporting the super-set of JS cases.

However, the specific piece of code being fallen over in your example is an `eval()` call which is being replaced (due to `vite` compiler warnings) in the next major release. We're expecting this to drop in the next few weeks. I suspect there is a non-trivial chance that may improve the chances of `shadow-cljs` being able to successfully compile.

We don't officially support `shadow-cljs`, so I am unable to offer specific support beyond this.

**Comment by armincerf** [comment]
> Hi @armincerf, thanks for reporting this.
> 
> On the surface, this appears to be a bug or incompatibility in the `shadow-cljs` compiler, as `changeCb` is a function parameter name that is referenced from a templated function call in the Charts codebase. I browsed the `shadow-cljs` GitHub issues and can see several similar `ReferenceError` issues closed in the past, so would guess they are still closing the gap on supporting the super-set of JS cases.
> 
> However, the specific piece of code being fallen over in your example is an `eval()` call which is being replaced (due to `vite` compiler warnings) in the next major release. We're expecting this to drop in the next few weeks. I suspect there is a non-trivial chance that may improve the chances of `shadow-cljs` being able to successfully compile.
> 
> We don't officially support `shadow-cljs`, so I am unable to offer specific support beyond this.

Thanks, after looking into this further I don't think this is anything to do with shadow-cljs, but instead its the inability of the google closure compiler to handle the dynamically generated functions from `eval`. Once that `eval` code is removed hopefully things will start working
