### ISSUE TITLE
Request: add support for Aurelia

### ISSUE THREAD

**Issue by grandtiger** [ceolter/ag-grid#690]
I am new to the web technology stack and recently found this great data grid. Thanks for your hard work!

I am wondering if it's possible to add support for [Aurelia](http://aurelia.io/). Thanks a lot!

**Comment by ceolter** [comment]
it's not something i was considering, my team just isn't big enough to support another framework at this time, and i'm currently hitting the biggest ones (react and angularjs).

any reason why the native javascript version is a problem?

ideally Aurelia should be able to use the web components version.

**Comment by grandtiger** [comment]
@ceolter The native JavaScript version should work, but I don't know yet as I haven't started using Aurelia in my project. I'll let you know if I run into any issues. Thanks!

**Comment by jadhavajay** [comment]
It would be really great to have Aurelia support in ag-grid, as it is one of the three leading frameworks. Lot of people I know are choosing [Aurelia](https://vimeo.com/153090562) between three due to its simplicity and power.

Having said that, as @ceolter suggested, we should be able to use native JavaScript version.

I will give it a try and will share an update soon. I am currently evaluating both React, Angular 2 & Aurelia.

**Comment by ceolter** [comment]
sorry, it's just time vs value, getting react in took me a full week, and now i have to maintain it.
```
I am currently evaluating both React, Angular 2 & Aurelia
```
let me know what you think. i've just started to look at the Aurelia intro movie

**Comment by jadhavajay** [comment]
Sure @ceolter

**Comment by Ajaeel** [comment]
[Here](https://gist.github.com/Ajaeel/2c800928dff558eebe0a) is a sample code that I could get it working with Aurelia.

**Comment by Thanood** [comment]
I found that the web components version works like a charm just by inserting it in the view.
Just set ```agGrid.initialiseAgGridWithWebComponents();``` in Aurelia's ```main.js```.

**Comment by ceolter** [comment]
thanks for the feedback.

**Comment by Ajaeel** [comment]
Everything is working fine with both JavaScript & Web-Components version, however pagination is not working at all... :|  Digging the examples...

**Comment by ceolter** [comment]
pagination should be fine - there is nothing in it that's specific to any framework

**Comment by ceolter** [comment]
funny you mention web components - maybe i should drop support for  angular 2 as that's mean to support web components also!!!

**Comment by Ajaeel** [comment]
Finally got the pagination, selection working with Aurelia :). Learnt a lot about ag-grid call backs...

**Comment by ceolter** [comment]
```Learnt a lot about ag-grid call backs...```
do i need to improve the docs?

**Comment by grandtiger** [comment]
@Thanood @jadhavajay congratulations on getting ag-grid to work with Aurelia. could you kindly share some sample code on how to get them to work together? Thanks a lot!

**Comment by Thanood** [comment]
@grandtiger Look here for an oversimplified example. :wink: 
https://gist.run/?id=dd8307fdce4ae6e5f5acc2c38d667c06

**Comment by grandtiger** [comment]
@Thanood thanks a lot for your help! Unfortunately I am using the webpack version of the starter kit.  I took a different approach and got a basic static grid to show up, however, I have another issue with loading CSS in the html file.

In the html file, I have something like:
```
<div ref='myGrid' style="width: 100%; height: 100%; margin: 0px;"></div>
```
In the js file, I have something like:
```
var gridDiv = this.myGrid;
new agGrid.Grid(gridDiv, gridOptions);
```
Trouble with loading CSS file using the following:
```
<template>
    <require from="./css/styles.css"></require>
    ... ...
</template>
```

**Comment by Thanood** [comment]
Unfortunately, that's an unresolved issue in webpack-plugin: https://github.com/aurelia/webpack-plugin/issues/11

I think it works when you import the css in the js file (`import './css/styles.css'`).

**Comment by grandtiger** [comment]
@Thanood Thanks again, Daniel! This works indeed! Now I can move on with my prototyping. Have a great day!

**Comment by eekwong** [comment]
5.3 and 5.3.1 renders the table as like zero height ... @ https://gist.run/?id=dd8307fdce4ae6e5f5acc2c38d667c06

5.2.0 is showing.

**Comment by Thanood** [comment]
@eekwong 
Maybe it's because the gist can't find the css files..

```
Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.ag-grid.com/dist/ag-grid.css
Failed to load resource: the server responded with a status of 404 (Not Found)
https://www.ag-grid.com/dist/theme-blue.css
```

**Comment by ceolter** [comment]
thanks for all the chatter here everyone. i'll come back to this when i finally get around to create ag-grid-aurelia

**Comment by jadhavajay** [comment]
@eekwong I have the same issue with 5.3.x and 5.4.x. It does not show up the grid.
When I switched back to 5.2, everything works fine. Not sure what exactly is breaking up the working grid!

**Comment by don-bluelinegrid** [comment]
I am looking at using agGrid in a new commercial project.  This project is to be built with Aurelia framework.

I've looked through this discussion, and the various stop-gap solutions proposed.

@Thanood @jadhavajay 
You've provided very rough examples of "wrapping" the agGrid module in an Aurelia class.  Am I correct in assuming that in order to use all of the full functionality of the agGrid (like filtering, virtual scrolling, etc.), *every* function/callback would need to be wrapped in the Aurelia wrapper class?  Isn't this essentially then like building an aurelia-ui-toolkit bridge implementation?

@ceolter 
Have you looked at the aurelia-ui-toolkit bridge project, and the sample implementation and docs?  (https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-architecture/content/)  I would imagine this would get you very close to providing Aurelia compatibility, without having to start from scratch.

Don

**Comment by Thanood** [comment]
@don-bluelinegrid 
It seems you can call ag-grid functions from Aurelia's `ref` pointer.
In my gist above this is used for initialization: `this.myGrid.setGridOptions(this.gridOptions);`

I guess events would have to be subscribed to. But I'm not sure if the resulting view model is really a wrapper class. It can be used like a custom element anyway. I don't see the need for a wrapper class. Would you mind to elaborate on that thought?

Of course the bridge infrastructure gives you a lot but I'm biased since I also did such a bridge (Materialize). Also I'm not sure if that's the case for projects which are already matured. You get built-in docs with samples and a "build-for-all-targets" infrastructure, but ag-grid already has that.

**Comment by don-bluelinegrid** [comment]
> But I'm not sure if the resulting view model is really a wrapper class. It can be used like a custom element anyway. I don't see the need for a wrapper class. Would you mind to elaborate on that thought?

From my perspective, a "wrapper class" is a class that interfaces with, or "wraps", some other component/module which would otherwise not be easily usable - like a facade.  The thought behind a wrapper class to interface with the agGrid module, is that if we have a large application where we are likely to use multiple/many instances of the grid, we'd like to have a generic interface for creating and interacting with the instances - we would not want to have logic like this in each view-model.

> You get built-in docs with samples and a "build-for-all-targets" infrastructure, but ag-grid already has that.

Actually, the reason for this thread is that agGrid is not available for all targets - specifically not for WebPack or Aurelia.

**Comment by Thanood** [comment]
Well, we share the same view on a wrapper class then. 😃 
I could imagine making the column configuration and callbacks more declarative instead of doing that in JS.

**Comment by don-bluelinegrid** [comment]
@Thanood 

I've spent some time, and have gotten this working reasonably well in Aurelia (from a proof-of-concept perspective), with remote data calls and virtual paging.

I noticed your comment above (https://github.com/ceolter/ag-grid/issues/690#issuecomment-248138622):

> It seems you can call ag-grid functions from Aurelia's ref pointer.
In my gist above this is used for initialization: this.myGrid.setGridOptions(this.gridOptions);

When I do what your Gist shows, and I examine the ref variable in the view-model class, the variable appears to be a DOM Element object, not an ag-grid instance.  So, there would be no 'setGridOptions()' function there.

My html template:
```
<ag-grid id="eGridDiv" ref="cmtyMembersGrid" class="ag-blue" style="position: absolute;top: 90px;bottom: 50px;width: 100%;" columns.bind="gridColumns" rows.bind="selectedCommunityMembers" pagesize.bind="pageSize"></ag-grid>
```

My view-model:

```
  cmtyMembersGrid: any;

...
attached{
    this.cmtyMembersGrid.setGridOptions(this.gridOptions);
}
```

In the screen shot, you can see that the resulting bound ref variable holds a DOM Element, and not a grid instance object.  Have I missed something?

Don
![screen shot 2016-09-21 at 3 29 51 pm](https://cloud.githubusercontent.com/assets/19780097/18726045/b9121736-8010-11e6-9eec-b06d78af8f63.png)

**Comment by don-bluelinegrid** [comment]
@Thanood 

Please ignore last comment.

I see that in the debugger it displays the Element content, but the ref is to an object with a setOptions function available.

This approach does work well, much better than explicitly calling createGrid().

Don

**Comment by Thanood** [comment]
Just to clarify this: It works as a web-component (spec-wise). So yes, this is a DOM object but at the same time more than that.

**Comment by don-bluelinegrid** [comment]
@Thanood 

Daniel -

https://github.com/ceolter/ag-grid/issues/690#issuecomment-197348937
You said:

> I found that the web components version works like a charm 

I am using the web-components version, and it does seem to work fine - in the Chrome browser.  It is not working at all in Firefox or Safari, presumably because of a lack of web-component support in those browsers.

Can you share anything about your experience with this, and share any code about how to conditionally polyfill for web-components support?

Thanks,
Don

**Comment by Thanood** [comment]
@don-bluelinegrid 

The ag-grid documentation suggests using [webcomponents.js](http://cdnjs.com/libraries/webcomponentsjs) as a polyfill [here](https://www.ag-grid.com/best-web-component-data-grid/index.php).

But the docs also state:
> The examples on this page have been tested to work with latest versions of Chrome and Firefox on Windows. They failed using IE 11 and Safari on Windows.

While Polymer, another framework making extensive use of web-components, also uses webcomponents.js and shows all "evergreen" browsers (including Safari) to be supported:
https://www.polymer-project.org/1.0/docs/browsers

I've never run ag-grid outside of Chrome and I'm using MutationObserver polyfill from webcomponents.js (not the complete package).

**Comment by ceolter** [comment]
fyi ```The examples on this page have been tested to work with latest versions of Chrome and Firefox on Windows. They failed using IE 11 and Safari on Windows.``` -> I said that about one year ago - pretty much nobody is using Web Components - taking this assumption as hardly anyone has every asked a question to me about it. it is possible that my info on web components is out of date.

**Comment by swalters** [comment]
initial support added here: https://github.com/ceolter/ag-grid-aurelia

You can build that project and copy to node_modules in this project:
https://github.com/ceolter/ag-grid-aurelia-example

The edit and filter templates need completing.  I'm not an Aurelia expert so maybe those that are can take a look at how the cell rendering via template was accomplished.

**Comment by Thanood** [comment]
Personally, I think it's well done, @swalters 👍 

I think it would be great if ag-grid-aurelia would support the column templates donw in html, like this:

```html
<ag-grid-aurelia>
  <ag-grid-col field="skill">
    <img src="/images/skills/${skill}.png" width="16px" title="${skill}" />
  </ag-grid-col>
...
</ag-grid-aurelia>
```

But maybe this would be a little to "far off" from the original ag-grid which uses render functions, not sure about that.
I would also have to look up how it works exactly. I've done something similar [for a tree-view](https://github.com/Thanood/aurelia-tree-view/blob/master/src/tree-view/tree-node.js#L53-L70).

**Comment by swalters** [comment]
@Thanood the ag-grid-col is there and working.  I just ran out of time to get the example application finished.

Most of the work was already done in the angular 2 adapter.  I just removed all the angular2 specific code and worked out a few kinks for aurelia.

**Comment by Thanood** [comment]
Oh, I didn't see this. Great! 👍 
I'd be interested in these "kinks" btw. but I guess that would hijack this issue.. 😃

**Comment by swalters** [comment]
@Thanood I added the ability to include the cell template via markup.  Your tree-view example was very helpful.

**Comment by Thanood** [comment]
Glad to hear! 👍

**Comment by ceolter** [comment]
aurelia support now in, closing.
