### ISSUE TITLE
Grouping when using virtualisation possible?

### ISSUE THREAD

**Issue by jogibear9988** [ceolter/ag-grid#782]
Is it possible (and how) to use grouping when using virtualized data? (means server side pagination)

**Comment by ceolter** [comment]
no it's not possible when doing server side pagination. however this is something that a very large client is looking for, so i plan to implement it over the coming two months. you will need to do the grouping yourself on the server thought, then the virutal pagination will show the groups and lazy load the details when you expand the groups. this is already tracked by a client engagement, so closing the issue here!!

**Comment by raycashmore** [comment]
@ceolter Did you manage to make any progress on this?

**Comment by semko2m** [comment]
I am also interested in this ability.
Please inform us when you finish it.

Kind Regards
