### ISSUE TITLE
rowSelected fires on row de-selection

### ISSUE THREAD

**Issue by pauljoey** [ceolter/ag-grid#819]
In 4.0.5, when you click on a row, the `rowSelected` event is fired for the selected row and then again for the de-selected row. Documentation leads me to believe that this should not be the case. 

I believe that this is due to `node.selectThisNode(false)` firing the `rowSelected` event regardless of whether the node is being selected or de-selected, per below. 

https://github.com/ceolter/ag-grid/blob/master/src/ts/entities/rowNode.ts#L203
```js
RowNode.prototype.selectThisNode = function (newValue) {
        if (this.selected !== newValue) {
            this.selected = newValue;
            if (this.eventService) {
                this.eventService.dispatchEvent(RowNode.EVENT_ROW_SELECTED);
            }
            var event = { node: this };
            this.mainEventService.dispatchEvent(events_1.Events.EVENT_ROW_SELECTED, event);
        }
};
```

**Comment by ceolter** [comment]
this is as intended. the event has the node as a param, so you can check the selected state of the node. it used to be different, so maybe the docs are misleading. this is similar to how HTML checkboxes work, there is only one change event, there is not event for 'selected' vs 'unselected'.

if you can advise where in the docs you were mislead i can change.

**Comment by pauljoey** [comment]
Right at the top of the "events" page - https://ag-grid.com/javascript-grid-events/index.php

The `rowDeselected` event has been removed while the description for the `rowSelected` suggests that it only fires when a row is selected.

Rather than changing the behaviour of the `rowSelected` it might have been preferable to remove it (with a warning) then have users migrate to the (more appropriately-named) `selectionChanged` event.

**Comment by ceolter** [comment]
thanks. i've changed the docs (although won't be live until my next release).

the selectionChanged is not the same. take following example: grid had 10 rows selected. user then clicks a group with 5 rows (no containing any selected rows). then rowSelected gets fired 15 times (10 unselected, 5 selected) and selectionChanged gets called once at the end.

**Comment by pauljoey** [comment]
Ah, I understand. In that case `rowSelectionChanged` would be a suitable name :). I wouldn't necessarily suggest changing the event at this point - moving forward I would just like to make the comment that I find such strategies (remove + add instead of changing) preferable for evolving the API. 

Really happy with ag-grid, it's proving to be an excellent part of our application toolbox. Many thanks.

**Comment by grovesNL** [comment]
@ceolter Is there a way to get the aggregate of these events rather than handling each one? So rather than receiving 15 events like your example above, only receive a single event. The event would indicate that selection has changed in some way and doesn't tell you which nodes.

Currently I'm not sure how to know when I hit the 15th event (effectively the last event in a chain of selection events), so I'm not able to aggregate them effectively. I am only interested in the net effect of the events, not each of the individual select/deselect events. I want to call `gridApi.getSelectedRows()` after all the intermediate events have occurred.

**Comment by DominicTobias** [comment]
It's quite strange behaviour, for me I get two events and the previous selected node fires AFTER the new one. At least if it was the other way around it would be less likely to break things. Also both `event.type` are "rowSelected", but at least I can filter out the unwanted one with a `event.node.selected` check.

**Comment by splintor** [comment]
I agree this is a strange API, and would rather have a separate rowDeselected event.
Also, RowNode.selected is [marked as private in rowNode.ts](https://github.com/ag-grid/ag-grid/blob/master/src/ts/entities/rowNode.ts#L189), so we need to use casting in order to make the distinction between selection and de-selection.

**Comment by splintor** [comment]
Well, I now realized I can use the `node.isSelected()` method...

**Comment by blazehub** [comment]
Is their a way i can suppress the dispatch event call on calling setSelected()  ??

**Comment by madhurahuja** [comment]
> Well, I now realized I can use the `node.isSelected()` method...

This certainly helped! Just that instead of isSelected(), I found the attribute node.selected
