### ISSUE TITLE
Angular 1.x: Grid events do not trigger $digest cycle

### ISSUE THREAD

**Issue by etiennecrb** [ceolter/ag-grid#837]
Hello,
Thank you for your incredible work on ag-Grid.

We are migrating from ag-Grid 3.3.3 to 4.0.6 and we noticed that a scope manipulation inside a grid event callback doesn't update the view as if it was done outside of Angular JS's context. Now we need to wrap scope manipulation inside an $evalAsync, whereas there was no need for that in ag-Grid 3.3.3.

I created a plunker to show you the issue: [demo](https://plnkr.co/edit/tYxgJR6XsDuLXSaaZf5H)

Is this behavior intended?

**Comment by ceolter** [comment]
yes that's the intended behaviour. i found places that really slowed the grid down when calling back into angular. so took it out, so you call it only when you need it.

going forward i'm going to keep away from the frameworks as much as i can (angular, react etc), the grid is currently to tightly bound to Angular 1 which is hurting it. the other frameworks (ng2, react, web components) didn't get tangled into the grid in the same way and the grid is cleaner for it.

**Comment by jprince** [comment]
@ceolter first of all, thanks for all of your work on this grid; it's been a godsend for my team. I'd like to just suggest that you document this behavior on https://www.ag-grid.com/javascript-grid-events/index.php (under the Angular 1 section). While I suspected this was the case, upon running into the issue, I had to find this corresponding issue in order to confirm my suspicion.

**Comment by ceolter** [comment]
@jprince - cool, docs updated. will be in next release.

thanks for the kind words. can you expand a bit on " thanks for all of your work on this grid; it's been a godsend for my team." and I'll stick in on the testimonials page? convince others why ag-Grid is great!!!
