### ISSUE TITLE
support for max-height

### ISSUE THREAD

**Issue by supersabillon** [ceolter/ag-grid#849]
The docs say:

> If using % for your height, then make sure the container you are putting the grid into also has height specified, as the browser will fit the div according to a percentage of the parents height, and if the parent has no height, then this % will always be zero. If your grid is not using all the space you think it should, then put a border on the grid's div and see if that's the size you want (the grid will fill this div). If it is not the size you want, then you have a CSS layout issue to solve outside of the grid.

If the grid has 100% height and the container div has a height of 500px, it works as expected. But it ignores the container if you use max-height instead of height.

It is possible to add support for max-height? This would be helpful when you're not sure how much data will come back from server and 500px (for example) might me too big.

**Comment by EndarValuk** [comment]
@supersabillon you can always use on grid(75% of visual height, e.g.):
`style="height: calc(75vh)"`

**Comment by ceolter** [comment]
the grid will fill the height of the grid you put it into. so if you put max-height on your div, no reason why the grid will not use it accordingly.

i tested this with the main demo page as follows and it worked:

```
        <div style="padding-top: 98px; height: 100%; max-height: 500px; width: 100%;">
            <div id="myGrid" style="height: 100%;" class="ag-fresh"></div>
        </div>
```

**Comment by AG-Zoheil** [comment]
Hi @ata1704,

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue from **over 7 years ago**.

The grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
