### ISSUE TITLE
sizeColumnsToFit all the time

### ISSUE THREAD

**Issue by BesatZardosht** [ceolter/ag-grid#860]
Thanks for AMAZING job!

I what to be able to resize the columns in a way that the sum of all columns' width would be grid width all the time. For example if I make a column bigger it would make another column smaller to fit them all in grid width.
Is it possible? If yes, how?

I would appreciate any help.

**Comment by ceolter** [comment]
i think that's to specific to be included in the grid, at least in the medium term! if you want to try something yourself, start with listening for the columnResized events.

doing your own implementation would be easier, as then you won't have to worry about items not relevant to you, eg if your not using column grouping, you don't need to consider it, or if you are, your solution can assume grouping and ignore when not.

**Comment by dennisteo** [comment]
Yes! This is a really nice request and it is not easy to be implemented.
I tried but I calling the sizeColumnsToFit() on columnResized event, falls into infinite loop.

**Comment by pdavin** [comment]
I would also like this ability. @ceolter, your suggestion to use columnResized event doesn't work because calling sizeColumnsToFit() in response to that triggers another columnResized event, creating an infinite loop. 

I don't understand dennisteo's suggestion of using setTimeout - wouldn't that still make an infinite loop, just a slightly slower one?

It's seems like the only way to do this would be to create a columnResized event that is only fired for manual resizes (user initiated). I don't need an event to be fired to let me know I called sizeColumnsToFit(). :) 

Alternatively sizeColumnsToFit() could have a stopPropagation parameter added.

**Comment by Ketec** [comment]
Came across this issue today - infinite loops because of it.  
I cannot even distinguish user resize and systemic column resize events. 
It needs type/source or the toFit() needs a preventEvent flag.
