### ISSUE TITLE
There are no styles for ag-header-menu-icon in new Theming API

### ISSUE THREAD

**Issue by Eugeno** [ceolter/ag-grid#8774]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
![image](https://github.com/user-attachments/assets/870d3f74-8cca-4418-9a50-cf5258ac1f93)

**Expected behavior**
https://www.ag-grid.com/examples/column-menu/column-menu-api/modules/angular/

* **AG Grid version:** 32.2.0

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: AG-13088

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

In the meantime, it is possible to work around this using some css, please see this example: https://plnkr.co/edit/l5SDvYDMJUwkuM96?open=main.js

Thanks again for bringing this up with us.

Kind regards,
Zoheil
