### ISSUE TITLE
New selection API misses a lot of scenarios that was possible with the old one

### ISSUE THREAD

**Issue by amirsarfarW** [ceolter/ag-grid#8805]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I have this code using 32.0.2

```
{
  rowSelection: "multiple",
  enableRangeSelection: true
} 
```

but the new API docs suggest that I have to pass `selection.mode` for both of these properties

how is this possible?

**Current behavior**

I can not have range selection and multi row selection at the same time

**Expected behavior**

I want it to behave like older version

**Please tell us about your environment:** Irrelevant

* **AG Grid version:** 32.2.0

* **Browser:** Irrelevant

* **Language:** Irrelevant

**Comment by AG-Zoheil** [comment]
Hello

Thank you for the suggestion.

As of version `32.2` we have made row selection and cell/range selection mutually exclusive due to the clashes and causes of inconsistency in behaviour when having both enabled at the same time.

However, please note that we are considering introducing an option to allow cellSelection + rowSelection **with checkboxes only**. Selection of one type would reset (undo) the selection of the other type, but both would be possible (enabled) at the same time.

This would allow users to utilise both types of selection whilst still protecting the grid from inconsistencies.

We have added this requirement to our backlog and we are tracking it with the following reference: **AG-12929**

Please note that cellSelection is an enterprise feature. As an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

You can follow the status of this item on the product pipeline page::
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
