### ISSUE TITLE
[Typescript] Issues Importing Theming API in AG Grid

### ISSUE THREAD

**Issue by jiy00nn** [ceolter/ag-grid#8810]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When attempting to use AG Grid's theming API with TypeScript, there are issues importing theme methods like themeQuartz. The errors encountered depend on the import path:
1. When following the [documentation](https://www.ag-grid.com/vue-data-grid/theming-api/#importing-a-built-in-theme) and using the import path:
    ```typescript
    import { themeQuartz } from '@ag-grid-community/theming';
    ```
    This results in the following error:
    ```
    Cannot find module '@ag-grid-community/theming' or its corresponding type declarations.ts-plugin(2307)
    ````
2. If I try importing from `ag-grid-community` as before
    ```typescript
    import { themeQuartz } from 'ag-grid-community';
    ````
    I encounter this error:
    ```
    Module '"ag-grid-community"' has no exported member 'themeQuartz'.ts-plugin(2305)
    ```
This makes it impossible to utilize the theming API as documented.

**Expected behavior**

The theming API methods, such as themeQuartz, should be importable without errors either via the documented path:
```typescript
import { themeQuartz } from '@ag-grid-community/theming';
```
or the standard `ag-grid-community` import path.

**Please tell us about your environment:**

* **AG Grid version:** 32.2.0

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0

* **Language:** Typescript 5.4.5

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for reporting this.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12924**

This will be fixed in our next release.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

In the meantime, please use the module npm install "@ag-grid-community/theming". Although this is not something we usually recommend for packages, it will be an adequate workaround until this is fixed.

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by GrantMStevens** [comment]
Any update here? This is still broken despite a minor semver update to 32.3 since this issue was created. I am using ag-grid-react and importing `@ag-grid-community/theming` does not resolve this issue like your comment and the docs suggest.
