### ISSUE TITLE
Row Selection Checkboxes Rendered After Pinned Columns

### ISSUE THREAD

**Issue by ivanThePleasant** [ceolter/ag-grid#8813]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
When a column has `pinned: 'left'` and `lockPosition: true` defined in column definitions, enabling row selection via `selectionColumnDef` puts checkbox column after any columns that are pinned and locked. This was behaving differently in AG Grid versions prior to 32.2.0

Expected behaviour.
Whenever `selectionColumnDef` has a property `pinned`, it should take precedence over any other columns and put the checkbox selection column to be the most left/right column (depending on pinned position)

Environment:
MacOS Sonoma 14.6.1
VSCode
Yarn
Next.js 14

AG Grid version:
32.2.0

Browser:
Brave

Language:
Typescript

Recording of the bug can be found here:
https://vimeo.com/1012729937?share=copy

**Comment by KN3LL2K** [comment]
I'm also trying to figure out a fix or workaround for this. It is not intuitive to have the selection box after the pinned columns

**Comment by jlpstolwijk** [comment]
you can put this in to always pin the checkboxes left:
```
  selectionColumnDef: {
        pinned: 'left'
      }
```
[Link to docs](https://www.ag-grid.com/angular-data-grid/row-selection-single-row/#customising-the-checkbox-column)

**Comment by ChristopheL77** [comment]
I have the same issue, and minimal example in sandbox :
[https://codesandbox.io/p/sandbox/column-pinning-forked-28dvf6](https://codesandbox.io/p/sandbox/column-pinning-forked-28dvf6)

![image](https://github.com/user-attachments/assets/ab287b17-9d5f-4eb2-b61f-a998b036828a)

**Comment by AG-Zoheil** [comment]
This is the expected behaviour. Please use the approach suggested by @jlpstolwijk.

Thank you!

**Comment by ChristopheL77** [comment]
> This is the expected behaviour. Please use the approach suggested by @jlpstolwijk.

Hello,
After first rendering, the 2 columns are displayed in the following order : Selection then PinnedLockLeft
After drag & drop, no matter where the column is dropped the checkboxes column is put as 2nd column.

Is it really the expected behaviour ?

Is there another way to lock the PinnedLockLeft position without using LockPosition that could prevent this issue ?

**Comment by scott-moxham** [comment]
> you can put this in to always pin the checkboxes left:
> 
> ```
>   selectionColumnDef: {
>         pinned: 'left'
>       }
> ```
> 
> [Link to docs](https://www.ag-grid.com/angular-data-grid/row-selection-single-row/#customising-the-checkbox-column)

This doesn't seem to work. The column I pinned is to the left of the selection column (which is also pinned left). Not the best screenshot as the pinned column is blank, but it does illustrate the point.

![image](https://github.com/user-attachments/assets/62c27b26-cb3b-4c62-8bb2-9d6ff9ce701b)

**Comment by scott-moxham** [comment]
> This is the expected behaviour. Please use the approach suggested by @jlpstolwijk.
> 
> Thank you!

As indicated above, the approach suggested by @jlpstolwijk doesn't work. The selection column is always the rightmost of the pinned left columns, but I need it to be the first!

**Comment by AG-Zoheil** [comment]
Hi,

I'm unable to replicate the behaviour you are reporting. See here: https://plnkr.co/edit/sb1dfOyAzrIbYTNE?open=main.js.

For any issues, please always provide a plunker which you can easily fork from our documentation.

Thanks

**Comment by ChristopheL77** [comment]
Just add lockPosition: true in your plnkr.co on column # as I did in codesandbox.

**Comment by scott-moxham** [comment]
@AG-Zoheil
It only seems to work if you specify rowSelection, which is deprecated.
If you instead use the new selection property in the GridOptions, it breaks.
In this example, it actually breaks more than my implementation and the selection column seems to be hidden.
It's quite possible that I've done something stupid though 😊

https://plnkr.co/edit/83XGx0WFuLWoVW4m?open=main.js

**Comment by AG-Zoheil** [comment]
Hi both,

I think the issue stems from looking at this via different versions.

I am using `32.2.1` which is our latest patch that was released last week.
Using that version you can see:

(1) @ChristopheL77 adding `lockPosition: true` doesn't move the checkbox column https://plnkr.co/edit/sb1dfOyAzrIbYTNE?open=main.js&preview

(2) @scott-moxham `rowSelection` is the correct `gridOption` to use and will display the checkbox column https://plnkr.co/edit/VJVw40LgFoWXBmIc?open=main.js

Apologies about the confusion, please upgrade to the latest version.

Kind regards,

**Comment by ChristopheL77** [comment]
> (1) @ChristopheL77 adding `lockPosition: true` doesn't move the checkbox column https://plnkr.co/edit/sb1dfOyAzrIbYTNE?open=main.js&preview

![image](https://github.com/user-attachments/assets/f3de4b03-d8fb-4406-9544-c463ee6a70c5)

Then drag and drop age into pinned panel

**Comment by scott-moxham** [comment]
@AG-Zoheil Thanks
I can see that in gridOptions.d.ts the property name 'selection' has now been changed to 'rowSelection' so that does explain the issues.
Also the separation of cellSelection will hopefully allow me to keep functionality in my product that uses both rowSelection and cellSelection features at the same time (slightly confusing but it's what the customer wanted!)

**Comment by AG-Zoheil** [comment]
Ah yes @ChristopheL77 - got there in the end.

Thanks - this has been raised as a bug and will be addressed. 

We are tracking it with the following reference: **AG-13013**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by ChristopheL77** [comment]
Thanks Zoheil :=) 
Have a nice day.

**Comment by scott-moxham** [comment]
@AG-Zoheil To update, after upgrading my app to 32.2.1 and using the `rowSelection` property, the checkbox column is still to the right of the other pinned column.
So far I am unable to reproduce this issue with plnkr - everything I try on plnkr works but everything I do on my app fails!
The only obvious difference between the two is that my app is using vue (with the <script><template> syntax style) and the columndefs and gridoptions are passed as separate params to the ag-grid rather than columndefs being defined within gridoptions.
I'm very new to vue so I don't fully understand the old style vue syntax that's used in the documentation examples and don't have time right now to work out how to build a new example from scratch. The app I'm working on is closed source so I can't give anyone access to that.
I will try to come back to this at some point, but my company strangely want me to work on customer requirements rather than tech debt 🙂 and it does work with the old deprecated options so not sure how soon this will be.

**Comment by SamChilversCyara** [comment]
I see the fix described in AG-13013 does not restore the functionality as it was pre 32.2.1. It was released in 32.3.0 and does not help the issue of degraded functionality on the Grid.

**Comment by btbritz** [comment]
+1 Please fix

**Comment by eliaspanagiotidis** [comment]
I am currently evaluating AG Grid Enterprise (version 32.3.3) as a potential grid solution for my company. I encountered a very similar issue that may not be resolved yet (although AG-13013 is not in the current pipeline). When using row grouping and aggregation, if I clear the "Row Groups" section and then add a new column to it, the "Group" column appears before the selection column. Additionally, some other columns become misaligned, with headers not matching their content.
This issue is a significant concern for us and may influence our decision against selecting AG Grid. Could you please confirm if this is a known issue that will be addressed or if there is a reasonable workaround available?

**Comment by yusuke-fukuhara** [comment]
Please fixxxxxx

**Comment by AG-Zoheil** [comment]
Hi, this issue was raised for the original report of "Row Selection Checkboxes Rendered After Pinned Columns" which has been addressed and delivered via A-13013.

If you have any other issues please raise a new GitHub issue and include a plunker displaying how to reproduce the issue. We'b be happy to then take a look.

Thank you for your understanding!

**Comment by Robroots** [comment]
This is still an issue on version 33.0.4. Using  GridOptions.rowSelection.headerCheckbox: true / checkbox: true,  when column is pinned - checkboxes are rendered in first not pinned column. If using depracted API and specifying column - all works fine.

**Comment by bndcts** [comment]
@Robroots are you sure it is still an issue for you? We had a similar problem because AG-Grid unpins pinned columns when the viewport [get's to small](https://www.ag-grid.com/javascript-data-grid/column-pinning/) (which is a feature but can be disabled).

Our problem was then that we persist the gridState meaning the columns are persisted as not being pinned.

**Comment by mezacanul** [comment]
It worked like this for me, no extra columns needed:
```javascript
`rowSelection={{
  mode: "multiRow",
  checkboxes: true,
  headerCheckbox: true,
  enableClickSelection: false, // Replaces suppressRowClickSelection
}}

selectionColumnDef={{
  pinned: "left",
}}`
```

**Comment by denisdobra10** [comment]
Yep, just solved today. As previously mentioned, just add 
`pinned: 'left'` into `selectionColumnDef`

So like for example, in Vue you'll pass this as prop to the table:
`:selection-column-def="{ pinned: 'left' }"`

**Comment by elramus** [comment]
I'm seeing `pinned` in `selectionColumnDef` only be respected if a fresh object is passed in on every render, ie: 
```tsx
selectionColumnDef={{ 
  pinned: 'left',
}}
```
It does not seem to respect it though if that object is memoized:
```tsx
const selectionColumnDef = useMemo((): SelectionColumnDef => {
  return {
    pinned: "left",
  };
}, []);
 
<AgGridReact
  selectionColumnDef={selectionColumnDef}
```
So easy enough to work around for now, but I wonder if this will create problems when React Compiler is being used more widespread and everything just gets memoized by default.
