### ISSUE TITLE
Grid scroll bar renders on top of context menu and charts

### ISSUE THREAD

**Issue by yorkeJohn** [ceolter/ag-grid#8834]
**I'm submitting a ...** bug report

**Current behavior**
Grid scroll bar renders on top of context menu and charts, receives pointer events:
![image](https://github.com/user-attachments/assets/8140157c-d0fc-4c87-86be-84dc9f8ca09b)
![image](https://github.com/user-attachments/assets/16568e70-c13a-44ce-a7e3-08872354d307)

**Expected behavior**
Scroll bar is not on top of context menu and charts and does not receive pointer events through the overlaid elements.

**Please tell us about your environment:**

Windows 11, React/Next.js, VSCode

* **AG Grid version:** 32.2.0

* **Browser:**
Firefox, not tested in other browsers

* **Language:** TypeScript 5.5.4

**Comment by yorkeJohn** [comment]
Note that this can be reproduced on any of the site demos: https://www.ag-grid.com/example/

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-13005**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
