### ISSUE TITLE
Getting selected rows in the SSRM

### ISSUE THREAD

**Issue by Eugeno** [ceolter/ag-grid#8870]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/ulDhiEUy73Fi1jlV?open=app.component.ts

**Current behavior**
I am not sure if this is a bug or if there is some misunderstanding on my part.

So, we have SSRM, and let's say there are only 5 records. I can select each row manually, and the `getSelectedRows()` method will display the actual state of the selected rows. 

However, if I want to select all 5 rows at once, according to [docs](https://www.ag-grid.com/angular-data-grid/server-side-model-selection), I should not use `getSelectedRows()` (and indeed, it returns an empty array). The alternative is `getServerSideSelectionState()`, but in that case, the `toggledNodes` field also shows an empty array.

As a result, there are odd situations where, for example, I select all records, then manually deselect and reselect one of them.

**Expected behavior**
Is there a way to get the current state from the API that reflects the checkboxes visible in the UI? 

From what I've found, this code seems to work:
```
params.api.forEachNode((node) => {
  // node.isSelected();
});
```
but I'm not sure if this is the correct solution.

* **AG Grid version:** 32.2.1

**Comment by AG-Zoheil** [comment]
Hi @Eugeno,

Thank you for submitting this on Github.

SSRM is an enterprise feature. As we do not provide support on Github, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here.

Kind regards,
Zoheil
