### ISSUE TITLE
Cannot load preconfigured filter set when filter value is not included in data row

### ISSUE THREAD

**Issue by malorieberthoin** [ceolter/ag-grid#8874]
**I'm submitting a ...**  (check one with "x")

```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

Hi,
I am currently using AG Grid 31.2.0 (enterprise).

I am currently working with "Set Filter", and I noticed that when a filter value is not present in the row data, the filter value is removed from the set. It seems to be an intended behavior.

In my use case, I save the AG-Grid `filterModel` config in a backend, to reload the table later as a preconfigured table.

The problem I encounter is that I cannot load my `filterModel`, if for example the table is empty.
It seems to be impossible to create a table with a preconfigured filter list selection, as the missing values in the rows will be discarded from the filter set.

One workaround could be to use the `filterParams.values` to set the values I have in my filterModel, but then I lose the ability to also have the filter list populated by the other values from the rows.

Do you have a solution or a workaround to achieve this kind of feature?

Kind regards,

**Comment by AG-Zoheil** [comment]
Hi,

Thank you for submitting this on Github.

The set filter is an enterprise feature. As we do not provide support on Github, I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here.

Kind regards,
Zoheil
