### ISSUE TITLE
Filters not removed when row data is set to empty as per v32

### ISSUE THREAD

**Issue by melon2504** [ceolter/ag-grid#8905]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
As per latest version **32**., if row data is set to empty after applying the filter, the filter isn't removed.
In versions before v32, filters used to get removed if the row data is empty

1)Apply a filter on any column
2)Click "Reset" button
3)The filter icon remains as well as the filter in the state
https://plnkr.co/edit/jhmr927tFdm5QqcC?open=index.tsx&preview

**Expected behavior**
Filters removed automatically on row data as empty array

1)Apply a filter on any column
2)Click "Reset" button
3)The filter is removed from the column & the state
https://plnkr.co/edit/FkSVv5JPXS8B40o2?open=index.tsx&preview

Is this now the expected behavior henceforth or is it a bug ?

* **AG Grid version:** X.X.X
32.2.1

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-13076**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
