### ISSUE TITLE
Getting error on "version" state property when appying initialState

### ISSUE THREAD

**Issue by melon2504** [ceolter/ag-grid#8923]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I'm unable to replicate the issue in plnkr but getting it in my project production env (screenshots attached). 

e.g. https://plnkr.co/edit/DfM5FkDJHkukLRTH?open=index.tsx

Scenario: I'm saving only some properties of grid state in backend, hence when applying it as initial state with no "version" property" to the grid, I get the following:
 
![image](https://github.com/user-attachments/assets/7ee79376-9887-4918-9bf2-f05b1f16446e)

![image](https://github.com/user-attachments/assets/94e8605f-c392-4297-80b8-d209aaf3176e)

![1](https://github.com/user-attachments/assets/b3d3efce-445f-44cf-9c87-33d023817f10)

* **AG Grid version:** X.X.X
32.2.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React, TypeScript

**Comment by spencermefford** [comment]
I am also experiencing this issue when upgrading from `32.1.0` to `32.2.2`.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12997**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
