### ISSUE TITLE
ShowContextMenuParams incompatible types

### ISSUE THREAD

**Issue by MudulOzan** [ceolter/ag-grid#8951]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

I am trying to call context menu in order to show contents in getContextMenuItems however I am having hard time putting rowNode, I tried to get row node using the api function geRowNode and also node returned from params which returns IRowNode however this expects RowNode, what am I missing here?

**Providing a Reproducible Scenario**
![image](https://github.com/user-attachments/assets/b7722db1-7416-4027-bda7-692ef6c2e88f)
```JS
    onCellClicked = (params: CellClickedEvent) => {
        const rowNode = params.api.getRowNode(params.node.id); // Returns IRowNode
        // params.node returns IRowNode
        params.api.showContextMenu({
            column: params.column,
            value: params.value,
            rowNode: rowNode // expects RowNode but incompatible with IRowNode
        });
    };
```

* **Language:** React.js TS 5.7.0

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-13139**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
