### ISSUE TITLE
skipRowGroups set to true in defaultExcelExportParams always breaks the export

### ISSUE THREAD

**Issue by eugeniobet** [ceolter/ag-grid#8957]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
When skipRowGroups is set to true in defaultExcelExportParams the export never works (results in a blank file).

**Expected behavior**
To work properly.

**Please tell us about your environment:**
Irrelevant.

* **AG Grid version:** 
* 32.2.1 and above

* **Browser:**
Chrome, Firefox

* **Language:** 
all

**Comment by eugeniobet** [comment]
come on.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-13112**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
