### ISSUE TITLE
Cell text selection and row highlight does not work well in latest Firefox but works in Chrome

### ISSUE THREAD

**Issue by theperiscope** [ceolter/ag-grid#9131]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
1. Open https://www.ag-grid.com/examples/cell-text-selection/cell-text-selection/modules/typescript/
2. When selecting text in a cell and moving up down with the mouse, unexpected text is highlighted in **Firefox**. Further, when mousewheel is used to scroll up/down fast, some random rows get highlighted in blue. Issues are not observed in Google Chrome browser.

**Expected behavior**
Cell text selection does not select text not selected by user with the mouse (like in Google Chrome at present)
Row highlights only selected row(s) when scrolling

**Please tell us about your environment:**
Windows 11 x64

* **AG Grid version:** latest, whatever is used in website demos

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

* **Language:** all

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12719**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
