### ISSUE TITLE
Question: Lessons learned writing this library in TypeScript

### ISSUE THREAD

**Issue by collinforrester** [ceolter/ag-grid#939]
We're diving into converting some of our most heavily used internal library components to TypeScript for several reasons.

I find it fascinating reading through this source code and seeing how you've structured the project, the code, and then publishing .d.ts files when you build.  It's been a huge help just reading and learning.

Do you guys have a blog or any of the authors have a blog where I can read about anything you've learned along the way?

I'm curious about the decorators (or annotations?) that you have in use too - why do you use them?  It seems you need every component to "initialize itself" but I can't tell if that's a result of your library components and the way you've written them or because of the fact they're ES6 classes and they get exported to ES5 in some cases.

**Comment by ceolter** [comment]
hi collinforrester,

first off, deffo use typescript over javascript, when in a large project, the strong typing helps so much, every time the typescript compiler picks up a message saying 'wrong type' or 'method doesn't exists' is a bug that is caught, not to mention all the classes (via the definition files) are self describing. plus making things private, these are all things all modern programming languages have and for good reason.

with regards the annotations that you see, there are two things going on here a) the IoC container - this is where you see @autowired, @postconstruct etc. these are all modelled around the Java Spring framework. we come from Java background and are applying the same methodologies. this is how we think IoC should be done - not like what you see in Angular or React (actually I don't know how it's done it React, so I shouldn't say, but I'm pretty sure it's not done right there either!! lol)

then there is the component and yes, the init - this is all work in progress. it is our intention to 'finish' the component design, and when it's done, it will work similar to Angular & React, in that components will be html tags that you can include in your templates. the 'init' will be called automatically with the parameters you specify in the html (or bind otherwise). when this is all done and dusted, depending on where we want to bring the ag-Grid project, we may document and release this and offer it as an alternative to the other frameworks out there that, in my opinion, are designed for glorified websites and not best for complex components or enterprise applications.

actually this the first time i've published these ideas, i hope this helps you understand what and why under the hood in ag-Grid.

**Comment by collinforrester** [comment]
Thanks for the detailed response, I'll keep any eye on the library and source as it matures.
