### ISSUE TITLE
Group double click bug

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#943]
If there is a table, with click on row to select it, and you group it with a parameter, creating a group the size of 1, when you double click the row, it selects & unselects it.
Does not happen when the group size is 2 or more

**Comment by ceolter** [comment]
either i could not reproduce, or i didn't understand what you are doing. i took one of my examples and set it to enable checkbox selection on the group and have group span entire row. dblclick on the group row expands the group, doesn't select. unless you click the checkbox - which does select as expected.

can you demonstrate in a plunker?

**Comment by AmitMY** [comment]
Sure, here is a plunker:
http://plnkr.co/edit/IWn5IDBa9roECqcv36Fv?p=preview

Open both groups.
Now that they are open, please double click the first row in the first group, It will select-unselect it,
Go to the second group, and double click the first row. It will just select it.

If you still don't see it, I might not explain myself very well, Ill make a short video.
Let me know

**Comment by ceolter** [comment]
ok fixed it. it will be in the next release (not yet planned, but this looks minor, so no rush??)

the problem has nothing to do with dbl click, it's single click.

a single click should not unselect a row. you need to have rowDeselection=true to allow this.

the problem was rooted in when groupSelectsChildren=true, then the groups were appearing in the selected list - they should not.

**Comment by AmitMY** [comment]
Very minor. Does not really a concern for me. Just found a bug and thought I should report, because you guys are actively perfecting the library

**Comment by ceolter** [comment]
cool. will be fixed in next release so.
