### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getColDefCol')

### ISSUE THREAD

**Issue by leey0818** [ceolter/ag-grid#9508]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
https://plnkr.co/edit/aC4SULwpuNDGjmeE?open=main.ts&preview (line 75)

A TypeError occurs when calling `params.getValue` function within the `filterValueGetter` option.

```javascript
const gridOptions = {
    columnDefs: [
        {
            ...,
            filterValueGetter: (params) => params.getValue("fieldKey"),  // <-- throw TypeError
        }
    ],
};
```

**Expected behavior**
The `getValue` function in the `IFilterParams` interface is not a target for migration, so it appears to be an internal bug.

**Please tell us about your environment:**

* **AG Grid version:** 33.0.1

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

* **Language:** ES5

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-13687**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
