### ISSUE TITLE
New version (31.1.3 +) of Ag Grid React is not working using the CDN Please guide me

### ISSUE THREAD

**Issue by ShivanandPrajapati** [ceolter/ag-grid#9540]
[x] support request

Requesting Community Support

Description
I want to use (32.2.0) version Ag Grid React as a CDN, and I have the following setup on my local project
Please provide me a demo working link with the CDN of the AG Grid and React.

When trying to load a basic setup i am getting errror TypeError: J.ComponentUtil.combineAttributesAndGridOptions is not a function;

Here is the local code copied here-
<html>
<head>
    <script src="https://www.unpkg.com/react@18.2.0/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@18.2.0/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
    <script src="https://unpkg.com/prop-types@15.6.0/prop-types.min.js"></script>
    <script src="https://unpkg.com/ag-grid-community@32.2.0/dist/package/main.cjs.js"></script>
    <script src="https://unpkg.com/ag-grid-react@32.2.0/dist/package/index.cjs.js"></script>
</head>
<body>
<div id='root'></div>
</body>
<script type="text/babel">
    const App = () => {
        const rowData = [
            {make: "Toyota", model: "Celica", price: 35000},
            {make: "Ford", model: "Mondeo", price: 32000},
            {make: "Porsche", model: "Boxter", price: 72000}
        ];

        return (
            <div className="ag-theme-alpine" style={{height: 400, width: 600}}>
                <AgGridReact.AgGridReact rowData={rowData}>
                    <AgGridReact.AgGridColumn field="make"></AgGridReact.AgGridColumn>
                    <AgGridReact.AgGridColumn field="model"></AgGridReact.AgGridColumn>
                    <AgGridReact.AgGridColumn field="price"></AgGridReact.AgGridColumn>
                </AgGridReact.AgGridReact>
            </div>
        );
    };

    let domContainer = document.querySelector("#root");
    ReactDOM.render(<App/>, domContainer);
</script>
</html>

**Comment by seanlandsman** [comment]
Hi - this is a bug. We'll be issuing a patch to fix this (and a few other issues) in release 33.0.3 tomorrow or Wednesday.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12124**

This should be fixed in the next release which will be a patch for v33 this week.

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by ShivanandPrajapati** [comment]
@AG-Zoheil and  @seanlandsman  ,

Thank you so much for resolving this bug so quickly! I really appreciate your team prompt response and effort in fixing the issue in the release of 33.0.3.
