### ISSUE TITLE
custom scrollbar

### ISSUE THREAD

**Issue by GalAzar** [ceolter/ag-grid#958]
I want to customize the scrollbar by css including controlling the scrollbar column width
is there a way it can be done?
Thanks
Gal

**Comment by AmitMY** [comment]
You can use custom CSS scrollbars.
Example: https://css-tricks.com/custom-scrollbars-in-webkit/

So deciding the scrollbar just for the grid (not entire browser) is this: (very basic style)

```
.ag-root ::-webkit-scrollbar {
    width: 2em;
    height: 2em
}
.ag-root ::-webkit-scrollbar-button {
    background: #ccc
}
.ag-root ::-webkit-scrollbar-track-piece {
    background: #888
}
.ag-root ::-webkit-scrollbar-thumb {
    background: #eee
}​
```

To test, just go to ag-grid.com, choose an example, and apply the css.

**Comment by GalAzar** [comment]
Thank you for you quick response!
I'm facing a problem when applying the css on the ag-body-viewport, when customizing the width of the vertical scrollbar (set to 6px) , after rendering, the column of the scrollbar is still in the original width
attached image:

![image](https://cloud.githubusercontent.com/assets/18511017/15985475/087966ae-2ff7-11e6-9645-c123067db2d8.png)


do you have any suggestions?
Thanks a lot!

**Comment by AmitMY** [comment]
No problem!
I didn't really understand you, can you fork this - http://plnkr.co/edit/IWn5IDBa9roECqcv36Fv?p=preview and just add your css? (so ill see a live example)

**Comment by ceolter** [comment]
isn't this a general 'how to style scrollbars' question rather than specific to ag-Grid?

in ag-Grid, we style the scrolls in the dark theme to be slimmer, the styles we use for this are (i included all scroll styling, the colors are not part of the sizing!!):

```
  ::-webkit-scrollbar
    width 12px
    height 12px
    background #302E2E

    &-thumb
      background-color #626262

  ::-webkit-scrollbar-corner
    background #302E2E
```

**Comment by Ruud-cb** [comment]
@ceolter I am using JQuery NiceScroll which eventually shows no scrollbar. I want the remaining space at the right, which is reserved for the scrollbar, to be 0px. I applied the style in css to my theme like you suggested but that didn't help anything.
![image](https://cloud.githubusercontent.com/assets/10037514/18867652/67021e66-84a5-11e6-9c31-38610949a609.png)

**Comment by ceolter** [comment]
@Ruud-cb  - i don't know off hand what is wrong. sorry. we also don't have the capacity in the team to look into using ag-Grid with all the different possible libraries, ie NiceScroll. so i'm afraid with this one, i can answer questions you have on ag-Grid, but as to why it's not working with NiceScroll, I'm not going to be much help.

**Comment by nkoterba** [comment]
@Ruud-cb Can you provide more details/information on how you integrated NiceScroll with ag-grid?

We are trying to do the same since styling `webkit` properties won't affect Firefox (and actually seems to double scrollbars in FF).

Sadly, there's no styling for FF scrollbars without using a Jquery plugin: http://stackoverflow.com/a/6165489/6641960

**Comment by nkoterba** [comment]
To those who stumble across this thread looking for a true cross browser solution, I was able to integrate Ag-grid with Perfect-Scrollbar (https://noraesae.github.io/perfect-scrollbar/) without too much pain.

Essentially, you need to add this to your project's CSS file: 
```css
.ag-body-viewport {
  position: relative; // Necessary for perfect scrollbar
}
```

Then I installed perfect-scrollbar using the NPM package.  I'm using Angular so in our controller that controls ag-grid, I use the `$element` service to grab `.ag-body-viewport` and initialize perfectScrollbar:
```javascript
        // Note: Using ES6; could CommonJS-require if using Browserify or other builders
        import perfectScrollbar from 'perfectScrollbar';

		this.viewport = this.$element.find('.ag-body-viewport')[0];
		perfectScrollbar.initialize(this.viewport);
```

I then made sure that whenever new data is loaded (we use virtual paging with ag-grid) or the grid is resized (`onGridSizeChanged`), I call:
```javascript
perfectScrollbar.update(this.viewport);
```

I also included the `perfect-scrollbar.css` file in my application to use the default *Perfect-Scrollbar* styles, but should be able to add your own CSS to match things.

** For safety, I call `perfectScrollbar.destroy(this.viewport)` when our controller is destroyed.  Make sure to do this too if it's necessary in your relevant framework **

**Comment by Ruud-cb** [comment]
@nkoterba Thanks for that example. I wonder, could you check if this doesn't have the issue I described with pinned columns? Do they scroll nicely at the same time?
And does ag-grid still reserve that space for the scrollbar when doing auto size to fit?

Do you still need an example for nice scroll? It actually is pretty much the same, just initiate it on the `.ag-body-viewport` class

`$('.ag-body-viewport').niceScroll();`

And in css you would need to do this:

`.ag-body-viewport { overflow: hidden !important; }`

**Comment by nkoterba** [comment]
@Ruud-cb I'm actually a little confused myself about what ag-grid is doing with regards to showing/displaying scrollbar space.

It's probably somewhat complicated by the fact we are using angular (so things in DOM get bound and laid out "late") as well as flexbox (again causes more time for browser to calculate and lay things out).

On some of our tables, Ag-grid shows the standard scrollbar spacer (on the right, 16 px in width):
![image](https://cloud.githubusercontent.com/assets/2508944/19353384/4275b056-9131-11e6-9fb2-29f187a5216f.png)

On other tables, Ag-grid doesn't show the scrollbar spacer at all (there are enough rows in this table to force a scrollbar; also of interest is if I resize the grid by resizing our window, etc. then all of a sudden the scrollbar spacer appears.  My guess is that ag-grid is laying out the grid *before* our data arrives so it doesn't think it needs a scrollbar.  Then the data arrives, but ag-grid doesn't subtract 16px from the last column's cells **until** the next time the grid is "resized"):
![image](https://cloud.githubusercontent.com/assets/2508944/19353405/55d70802-9131-11e6-9ed6-adecae51cbdc.png)

Perfect scrollbar hides the scrollbar when the area isn't **focused**.  Here's what it looks like when the scrollbar appears:
![image](https://cloud.githubusercontent.com/assets/2508944/19353459/7e31d6b0-9131-11e6-8831-55c86e3b73fc.png)

But on the non-spacer table when the scrollbar is shown:
![image](https://cloud.githubusercontent.com/assets/2508944/19353514/9e1d74e8-9131-11e6-9934-ab26091363cf.png)

Personally, I'm ok showing the spacer **all the time** because `perfect-scrollbar` when you hover over the scrollbar, grows the scrollbar to make it easier to scroll which nicely fills up the gap left by ag-grid.
![image](https://cloud.githubusercontent.com/assets/2508944/19353571/c9dd8d5c-9131-11e6-943f-2a8a95433d7e.png)

What I have *not* looked into yet, is when and how ag-grid calculates the space for the scrollbar and why in some cases it leaves a spacer for the scrollbar and in other cases it does not.

To specifically answer your questions:
> And does ag-grid still reserve that space for the scrollbar when doing auto size to fit?

- On some tables, it shows the spacer.  On others it does not.  A quick look to me indicates that internally ag-grid determines if a vertical scrollbar would appear (by calculating the height of the grid and how many rows it will display) and if so, since ag-grid specifically gives columns widths (e.g. `style="width: 75px"`), there's no way using CSS to **HIDE** the spacer unless you modify the last column's HEADER and CELL width property via CSS and add 16px to it.  I'm hoping @ceolter can chime in here and confirm this.
- So in terms of "hiding" the scrollbar spacer, unless there's some `ag-grid` *api* method or setting we can tweak, I think you're out of luck hiding the spacer without some nasty CSS manipulation.
- Essentially, what we want to tell ag-grid is to "even if my # of datarows would cause a y-overflow, don't subtract 16px from the last column's style width property"

> Do they scroll nicely at the same time?

- So pinned-right columns with a 3rd party scrollbar really don't play well.  Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/2508944/19354517/f8941578-9134-11e6-8e58-8756ab6bb6a8.png)

I get two scrollbars.  The rightmost scrollbar is 'ag-grids'; my 3rd party scrollbar is the one on the left.  Scrolling the panel on the left (the unpinned columns) does **NOT** scroll the column on the right.  However, scrolling the pinned column on the right, **does** scroll all columns correctly.  My guess is that my 3rd party scrollbar should be applied to the right-most column instead of `ag-body-viewport`.

When I use `ag-grid` default scrollbar implementation with a right-pinned column, everything scrolls correctly, *however*, it appears my columns are mis-aligned..it appears like ag-grid doesn't know to leave a spacer for the pinned-right column scrollbar. (@ceolter is it possible this is a bug in how ag-grid determines whether to create a scrollbar spacer with a right-pinned column?...the online example you give under Pinning https://www.ag-grid.com/javascript-grid-pinning/index.php only shows examples of left-pinned columns)  See pic:
![image](https://cloud.githubusercontent.com/assets/2508944/19354629/72d0ae78-9135-11e6-8adc-5cf80fa96a8a.png)

As a follow-up, with a right-pinned column, I switched my 3rd party scrollbar to apply to to `.ag-pinned-right-cols-viewport`.

Now I only get one scrollbar (but I still probably need to apply the 3rd party scrollbar to the unpinned columns for horizontal scrolling).  Everything scrolls smoothly and evenly.  The only issue is that my scrollbar on the right disappears!!! It appears that the 3rd party scrollbar is calculating it's "height" using the height of the entire contents/body of the pinned right column instead of just the right-column's viewport height.

Here's a picture (notice right-most scrollbar looks ok, bottom scrollbar is default ag-grid, which I'd need to replace with 3rd party).  Everything scrolls nicely and in sync though:
![image](https://cloud.githubusercontent.com/assets/2508944/19354957/9284087c-9136-11e6-80e4-4a6fc702a6c5.png)

**Comment by Ruud-cb** [comment]
@nkoterba thanks for your huge and well explained answer. Still sounds a bit like a drama :(.
Funny thing is: when we open the ag-grid on a touch device, only a little scrollbar appears when scrolling. Actually perfectly what we want. I don't know since what version that is, but I have 6.1 now. Maybe it would be possible to use these scrollbars as well on desktop. @ceolter , is this a ag-grid feature or is this done by the browser? If it is an ag-grid feature, could we somehow force ag-grid to always use these scrollbars? This is exactly what we need.

![image](https://cloud.githubusercontent.com/assets/10037514/19431304/41657294-9458-11e6-9ebe-4f301adcfc91.png)

Please consider re-opening this issue and mark it as a feature/bug?

**Comment by ceolter** [comment]
@Ruud-cb ag-Grid doesn't decide what scrollbar to use - it uses the stock scrollbar. if you want to customise, you use css to change the stock one.

the method for getting the scrollbar width you can see here:
https://github.com/ceolter/ag-grid/blob/master/src/ts/utils.ts#L546

basically i create a div with scrollbars and compare the width of the inner vs outer div (ie how much the scrolls remove).

the only item i can see as an issue, is i do this by adding to the document, maybe i should add to the grid, as then any style changes you make to the grid will be used.

btw, i don't add a spacer to the header, this is merely the result of a gap, by scrolling the header to match the body, this bit is left over.

**Comment by nkoterba** [comment]
@ceolter So I think the issue is not so much "styling" of the scrollbar as getting ag-grid to not take into account scrollbars.  In looking thru the code and the link you provided above, it appears that ag-grid is reducing the width of the viewport (and column widths) to leave space for the system's scrollbar when scrolling is present.

Since some 3rd party scrollbar replacements actually hide the scrollbar entirely or lay the custom scrollbar ON TOP of the div to scroll, it would be nice to have an option to tell `ag-grid` not to do any special "scrollbar" calculations

**Comment by ceolter** [comment]
@nkoterba ok i've just implemented property scrollbarWidth, if it exists, it will use this rather than work the width out itself. will be in next release.

**Comment by Surendranath26** [comment]
[Check this Link ](https://stackoverflow.com/a/57476456/5629298)perfect-scrollbar integration with  ag-Grid in angular7

**Comment by caueteixeira** [comment]
> To those who stumble across this thread looking for a true cross browser solution, I was able to integrate Ag-grid with Perfect-Scrollbar (https://noraesae.github.io/perfect-scrollbar/) without too much pain.
> 
> Essentially, you need to add this to your project's CSS file:
> 
> ```css
> .ag-body-viewport {
>   position: relative; // Necessary for perfect scrollbar
> }
> ```
> 
> Then I installed perfect-scrollbar using the NPM package. I'm using Angular so in our controller that controls ag-grid, I use the `$element` service to grab `.ag-body-viewport` and initialize perfectScrollbar:
> 
> ```js
>         // Note: Using ES6; could CommonJS-require if using Browserify or other builders
>         import perfectScrollbar from 'perfectScrollbar';
> 
>         this.viewport = this.$element.find('.ag-body-viewport')[0];
>         perfectScrollbar.initialize(this.viewport);
> ```
> 
> I then made sure that whenever new data is loaded (we use virtual paging with ag-grid) or the grid is resized (`onGridSizeChanged`), I call:
> 
> ```js
> perfectScrollbar.update(this.viewport);
> ```
> 
> I also included the `perfect-scrollbar.css` file in my application to use the default _Perfect-Scrollbar_ styles, but should be able to add your own CSS to match things.
> 
> ** For safety, I call `perfectScrollbar.destroy(this.viewport)` when our controller is destroyed. Make sure to do this too if it's necessary in your relevant framework **

For seemless scrolling on resize, include the following on your scss file as well:

    .ag-center-cols-viewport{
      overflow: hidden !important;
    }

**Comment by papastepano** [comment]
I have achieved adjusting ag grid's width to the width of a custom scrollbar by:
```typescript
gridOptions: GridOptions = {
    alwaysShowVerticalScroll: true,
    scrollbarWidth: 8, // the width of my custom scrollbar in px
}
````

**Comment by AnatolyGavrilov** [comment]
> You can use custom CSS scrollbars. Example: https://css-tricks.com/custom-scrollbars-in-webkit/
> 
> So deciding the scrollbar just for the grid (not entire browser) is this: (very basic style)
> 
> ```
> .ag-root ::-webkit-scrollbar {
>     width: 2em;
>     height: 2em
> }
> .ag-root ::-webkit-scrollbar-button {
>     background: #ccc
> }
> .ag-root ::-webkit-scrollbar-track-piece {
>     background: #888
> }
> .ag-root ::-webkit-scrollbar-thumb {
>     background: #eee
> }​
> ```
> 
> To test, just go to ag-grid.com, choose an example, and apply the css.

Bless you!
