### ISSUE TITLE
v33 module support

### ISSUE THREAD

**Issue by n19htz** [ceolter/ag-grid#9586]
Hello,

I noticed in the recent version (33+) of AG Grid, there seems to be confusion about the usage of modules. Could you please clarify whether support for AG Grid modules is no longer available?

Here are the modules I'm currently using in my project:

{
  "@ag-grid-community/angular": "32.3.3",
  "@ag-grid-community/client-side-row-model": "32.3.3",
  "@ag-grid-community/csv-export": "32.3.3",
  "@ag-grid-community/styles": "32.3.3",
  "@ag-grid-enterprise/clipboard": "32.3.3",
  "@ag-grid-enterprise/column-tool-panel": "32.3.3",
  "@ag-grid-enterprise/excel-export": "32.3.3",
  "@ag-grid-enterprise/filter-tool-panel": "32.3.3",
  "@ag-grid-enterprise/master-detail": "32.3.3",
  "@ag-grid-enterprise/menu": "32.3.3",
  "@ag-grid-enterprise/multi-filter": "32.3.3",
  "@ag-grid-enterprise/range-selection": "32.3.3",
  "@ag-grid-enterprise/rich-select": "32.3.3",
  "@ag-grid-enterprise/row-grouping": "32.3.3",
  "@ag-grid-enterprise/set-filter": "32.3.3",
  "@ag-grid-enterprise/status-bar": "32.3.3"
}

Thank you for your clarification!

**Comment by n19htz** [comment]
From all those modules, only @ag-grid-community/styles@33.0.2 is available on the NPM registry. The rest are still at version 32.

**Comment by StephenCooper** [comment]
In v33 due to improvements to treeshaing there is no longer a requirement for separate NPM feature modules to achieve tree shaking. This means we can simply export all the modules from either `ag-grid-community` or `ag-grid-enterprise` as follows:

- @ag-grid-community/angular is replaced with ag-grid-angular
- All @ag-grid-community/** packages are replaced with ag-grid-community
  - Apart from @ag-grid-community/locale which remains unchanged.
- All @ag-grid-enterprise/** packages are replaced with ag-grid-enterprise.

So in your case you can simplify your dependencies to:

```
{
  "ag-grid-angular" : "^33.0.0",
  "ag-grid-community" : "^33.0.0",
  "ag-grid-enterprise" : "^33.0.0"
}
```

You can then use our codemod tool to update all the import paths in your application so that you do not have to do this manually. 

```
npx @ag-grid-devtools/cli@33.0 migrate --from=32
```

For more details please see the [v33 Migration Guide.](https://ag-grid.com/javascript-data-grid/upgrading-to-ag-grid-33/)

**Comment by brendonco** [comment]
@StephenCooper how is lazy loading and treeshaking works here in v33?  any sample configuration doc?

**Comment by StephenCooper** [comment]
@brendonco For tree shaking you will need to chose which modules you need based on the features you require. This tool on our docs can help you do that. https://www.ag-grid.com/javascript-data-grid/modules/#selecting-modules 

Also our examples on the documentation show which modules are required for that feature. 

This only covers treeshaking. For lazy loading and code splitting that will depend on the framework you are using and how you setup your application. 

For Angular here are some relevant documentation to setup these

Lazy load via routes

https://angular.dev/guide/routing/common-router-tasks#lazy-loading

Lazy Load component with defer

https://angular.dev/guide/templates/defer

For React you could use lazy and suspense:
React lazy https://react.dev/reference/react/lazy#reference 
Web Dev https://web.dev/articles/code-splitting-suspense
