### ISSUE TITLE
Tweak infinite scrolling behavior (a bit buggy and not supporting features)

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#960]
I have a few points that I think the grid should implement:
- `getRows` - if it is the first get rows / new filter / new sorting order: showLoadinOverlay. (on server side getting, sorting, and filtering)
- `params.successCallback` - must also call hideOverlay
- Is there a `pramas.failureCallback`? couln't find one
- `ag-grid: cannot do quick filtering when doing virtual paging` - understandable. Is there a way to create something like the quick filter, with an apply button?
- `Uncaught selectAll only available with norma row model, ie not virtual pagination` - this doesn't make sense to me.... I think it should select all of the rows currently loaded rows
- instead of params.successCallback, wouldn't you rather use `resolve` and `reject`?
- ag-Grid: getDataAsCsv is only available for standard row model - why?

Also, encountered a bug: (I followed your example, so don't know why)
Even after the table loads, when I click on the 3 bars icon (for filtering), it throws:

> Uncaught TypeError: this.rowModel.forEachLeafNode is not a function

**Comment by ceolter** [comment]
ag-grid: cannot do quick filtering when doing virtual paging - understandable. Is there a way to create something like the quick filter, with an apply button?
=> true - and yes it would be nice to have one and have it passed back to the server side with the other filters.

Uncaught TypeError: this.rowModel.forEachLeafNode is not a function
=> you must be using the set filter - which won't work in virtual pagination - as it can't find the values to include in the set.

Is there a pramas.failureCallback? couln't find one
=> yes, it's called failCallback

instead of params.successCallback, wouldn't you rather use resolve and reject?
=> possibly - i have avoided using promises in the grid as i find they can make the design more complex when trying to follow things through. but this is probably just me - i am not used to working with promises so it may only make it more complex in my head.

hide / show overlay
=> yes possibly.

what i would like to do is go back over the paging and virtual pagination and do a 'second sweep', cleaning up all issues like you raise, and also bringing in an API for both (eg purge cache, set starting position etc). it's just a matter of priorities and right now my head is all in pivoting! (yes i know i said that in the other issue also, but it's true, pivoting is taking a lot of my brain cell right now)

**Comment by AmitMY** [comment]
Thanks for considering!
Yeah, I'm not really sure what pivoting is, just read it is 'a powerful feature of excel' - so when it will come out my boss will probably like it. Any time frame on that? (not pushing, just interested)

I'm trying to help other insignificant issues here so you'll have more time for mine :) (And because I love helping people)

Thanks again

**Comment by ceolter** [comment]
thanks for looking to help out - it's appreciated, even if i don't have the time to properly respond.

re pivoting, you can see progress on the youtube clip i posted:
https://youtu.be/jCId-Lbg_6k

approx 2 weeks (but i normally underestimate these things, so maybe 3 or 4)

**Comment by AmitMY** [comment]
That is really cool!

**Comment by ceolter** [comment]
this is an old issue, since then pivoting has gotten released and invintate scrolling has gotten an overhaul. so closing this issue.

**Comment by AmitMY** [comment]
I didn't really fiddle with infinite scrolling since then, as I found it unfinished. glad it was overhauled, if I'll have problems with the new version I will create a new issue.
Thanks
