### ISSUE TITLE
CSV Export does not include group footer or floating bottom row

### ISSUE THREAD

**Issue by ataft** [ceolter/ag-grid#982]
The export to CSV feature does show the group header, but does not include group footer or floating bottom row even though the "groupSuppressBlankHeader: true" and "groupIncludeFooter: true" grid options are set.

Here's an example: https://jsfiddle.net/andytaft/xbwxv65g/8/

**Comment by ceolter** [comment]
yes you are right.

the 'footer' concept is introduced in the GUI part, for when the grid decides what rows to render (ie how many groups are open decides what rows are rendered). 

when doing export, the export goes straight to the model, so it doesn't use the same header/footer detail as the grid does.

so at this point, i'm contemplating taking this property out, as it doesn't make sense in the export.

would that be ok?

**Comment by ceolter** [comment]
ti have updated the documentation to be more clear on what the export does

```
What Gets Exported
The same data that is in the grid gets exported, but none of the GUI representation of the data will be. What this means is:

The raw values, and not the result of cellRenderer, will get used, meaning:
cellRenderers will NOT be used.
valueGetters will be used.
cellFormatters will NOT be used (use processCellCallback instead).
If row grouping, all data will be exported regardless of groups open or closed.
If row grouping with footers (groupIncludeFooter=true) the footers will NOT be used - this is a GUI addition that happens for displaying the data in the grid.
```

**Comment by ceolter** [comment]
docs will be updated on next release

**Comment by saifeer** [comment]
Hey @ceolter, 
I see you have closed the issue but I have a use case where it seems to make sense to export the floating bottom rows - 
I am currently using the floating row to create a summary aggregation record for the data that I show (no groupings just simple summaries). I listen to the model update event to refresh my summary data by recalculating the summaries based on the rows to display.

This works fine but the issue is when I try to export the data. It skips the floating bottom row completely and although I can add a customer footer in the CSV, its not the same as adding a row of data in the CSV. 

If there is no way to export the rendered summary, would there be a way to add a custom row to the export that I can populate with the summary data I already have from the grid? I could hard-code the data in the custom footer string but that would seem too much of a hack to actually have columns and CSV separators hard-coded in the export function. (plus what happens when someone is using a different CSV separator and I am hard coding comma.)

Is there a better and more efficient way of doing this? 

Thanks
S

**Comment by ceolter** [comment]
@saifeer just finished implementing floating rows in csv export. will be in next release.

**Comment by saifeer** [comment]
That's awesome! Nice work man! Much appreciated
